- README.rst
- docs/release-notes.md
- stbt/__init__.py
- tests/test-stbt-py.sh
This makes it consistent with the other functions such as `match()`, and makes it more useful with a hypothetical `wait_until`, allowing constructions such as:
assert wait_until(is_screen_black)
> API: `is_screen_black`: Make `frame` parameter optional

- stbt/__init__.py
Within the as_precondition context manager, whenever a UITestFailure
is raised, log the original exception's traceback with stbt.debug.
This makes it easier to determine exactly where and why a precondition
has failed, as the PreconditionError that is raised within as_precondition
only shows the message of the original exception, not the traceback.
> stbt.py: Modified as_precondition to include original traceback

- .travis.yml
- _stbt/logging.py
- docs/release-notes.md
- stbt-run
- tests/test-stbt-batch.sh
- tests/test_ocr.py
When stbt is outputting to a terminal it will choose the encoding of the
stdout and stderr streams based on the LOCALE in use.  When it doesn't
detect a TTY attached to stdout/stderr it will default to ASCII output.
`stbt run` outputs directly to the terminal.  `stbt batch run` redirects
the output of `stbt run` to `tee` and then to a log file.
This means that if you `print u"Alfonso Cuarón"` in a test script (or
more likely `print` the output of `stbt.ocr`) whether you get a
`UnicodeEncodeError` will depend on whether you are using `stbt run` or
`stbt batch run`.
Python 3 fixes this issue by falling back to encoding as utf-8 rather than
ASCII.
This is technically a backwards-incompatible change but I don't expect that
it will break any test-scripts in the wild.  In fact I think the …
> stbt batch run: Fix `UnicodeEncodeError` when printing Unicode strings

- docs/getting-started.md
- docs/release-notes.md
- stbt-record
- stbt-run
- tests/test-stbt-batch.sh
- tests/test-stbt-control.sh
- tests/test-stbt-record.sh
- tests/test-stbt-run.sh
- tests/test_functions.py
You can now run a test with:
stbt run test.py::my_test_function_name
This mimics py.test's command line interface, except that `stbt run test.py` won't run all `test_*` functions in the file.
This brings `stbt` to parity with the stb-tester ᴏɴᴇ appliance.
TODO:
* ~~Update tab-completion script for `stbt run` and `stbt batch run`.~~
> stbt-run: Allow running tests by test name

- stbt-completion
- tests/test_functions.py
Tab-completion for the feature added in #249.
TODO:
> stbt-completion: Complete python function names

- stbt-batch.d/templates/index.html
tablequeryjs (the library we use for browser-side filtering of testrun
results) looks at the table's first row (after the headings) to
determine what each column's data type is. For this it uses momentjs,
a third-party library bundled by tablequeryjs.
Sometimes it gets it wrong. For example it thinks that a particular git
sha is a timestamp, and so you can't search for textual matches on the
"git sha" column.
Another (more serious) bug is that if the content of a table-cell
(in the first row after the headings) is longer than ~150 characters,
there's a null-dereference error somewhere deep in momentjs and the
entire page breaks, not just the search.
This seems to fix it. I'm not interested in writing an automated
regression test for it. At some point hopefully soon we're going to …
> stbt batch summary report: Hardcode column types for tablequeryjs

- stbt-run
- tests/test-stbt-run.sh
when running a test using the `script.py::function` scheme.  This makes `stbt run` behave more like `python script.py` and makes it easier to import other files in the same directory.
The old-style one test-script per file approach already does this.
> stbt run: Add the script's directory to PYTHONPATH

- stbt-batch.d/templates/index.html
For bugfixes (https://github.com/asimihsan/tablequeryjs/issues/19 and
https://github.com/asimihsan/tablequeryjs/issues/21) and for
`set_filter` so we don't have to use undocumented internal tablequery
APIs.
This means I can revert #258 which was a bit of a hack.
> Upgrade tablequeryjs to 0.18

- stbt-batch.d/run
- tests/test-stbt-batch.sh
`stbt batch run` parses its arguments into a list of test cases (with `parse_test_args` which is then piped into a while loop which executes each test in order.  If one of the test cases were to read from stdin the list of tests would be consumed by the test case, not by the test-runner causing all subsequent tests to be skipped.
This commit fixes that bug by redirecting stdin to `/dev/null` for test runs.
> stbt batch: Fix test scripts messing up test list by reading from stdin

- README.rst
- docs/release-notes.md
- stbt/__init__.py
- tests/test_match.py
`MatchResult.image` now returns the template image name as passed to `stbt.match`, rather than the absolute path to the template.  This is the previously documented behaviour and allows constructs like:
m = stbt.wait_until(
lambda: stbt.match("success.png") or stbt.match("error.png"))
assert m
if m.image == "error.png":
recover()
This is technically a breaking change but I don't expect that it will break any user scripts.
> API: Make `MatchResult.image` match what was passed to `match`

- stbt-batch
The help message of `stbt batch` says that "For help on a specific
subcommand do `stbt batch <subcommand> --help`". However, running
`stbt batch run --help` exits with status code 1 saying
"Invalid option '--'. Use '-h' for help."
Advise users to use `stbt batch <subcommand> -h` to avoid this error.
> stbt-batch: Fix inconsistency in help message

- Makefile
- stbt-completion
- stbt-run
- tests/test-stbt-batch.sh
- tests/test-stbt-run.sh
- tests/test_functions.py
`assert` takes an optional error message, and if you don't specify it,
then the `str(AssertionError)` is blank. In the `stbt batch` report,
you just see "AssertionError:" as the failure reason.
With this commit, the failure reason will show the line of code that
raised the `AssertionError`, but only if the `assert` statement was not
given an explicit error message.
This isn't perfect: For multi-line `assert` statements, you'll only see
the last line. But it's still very useful in most cases.
> stbt run: Print details of failed assert statement

- tests/test-stbt-py.sh
In 68983e0 we stopped running integration tests with `PYTHONPATH` set.
test_clock_visualisation requires tesseract 3.03, and at the beginning of the test we check this by running a little Python snippet.  The return code of this snippet was to distinguish between tesseract versions, but it didn't make a distinction between version 3.02 being installed and any other miscellaneous error.  This silently caused this test to be skipped.
This commit fixes this issue.  Thankfully the test still passes.
> test_clock_visualisation: Fix skipping logic broken in 68983e0

- tests/test-camera.sh
- tests/test-stbt-batch.sh
The [log on Travis-CI](https://travis-ci.org/stb-tester/stb-tester/builds/60657799) says:
```
test_that_stbt_batch_reports_results_directory... FAIL
Showing '/tmp/stb-tester.rpC/log':
tests/test.py ...
[2015-04-30 08:00:07.380596 +0000]  libdc1394 error: Failed to initialize libdc1394
[2015-04-30 08:00:08.034678 +0000]  stbt-run: Arguments:
[2015-04-30 08:00:08.034777 +0000]  control: test
[2015-04-30 08:00:08.034809 +0000]  save_trace: None
[2015-04-30 08:00:08.034839 +0000]  verbose: 1
[2015-04-30 08:00:08.034867 +0000]  args: []
[2015-04-30 08:00:08.034895 +0000]  source_pipeline: videotestsrc is-live=true ! video/x-raw,format=BGR,width=320,height=240
[2015-04-30 08:00:08.034928 +0000]  script: /tmp/stb-tester.rpC/tests/test.py
[2015-04-30 08:00:08.034960 +0000]  restart_source: False …
```
> Fix test_that_stbt_batch_reports_results_directory

- docs/release-notes.md
- stbt/__init__.py
`stbt.press` uses `draw_text` to draw the pressed key name on the output
video stream for 3 seconds, and I always found it very confusing when
there were several keypresses in quick succession -- is the latest
keypress at the top or at the bottom? Now it is very clear.
TODO:
> stbt.draw_text: Fade out older text

- docs/release-notes.md
- stbt-batch.d/run.py
The `--shuffle` option runs the given test cases in a random order.  This can be useful if you have structured your test pack as a large number of short targeted tests.  You can then use:
stbt batch run --shuffle \
epg.py::test1 epg.py::test2 menu.py::test1 menu.py::test2 ...
to attempt a random walk of different journeys though your stb UI.  This can be particularly effective at finding hard to trigger bugs and get more value out of the test-cases you have written.
Some tests may take much longer than other tests, which will then use up all your soaking time.  To work around that we measure how long each test takes the first time it is run, and use that as a weighting when choosing the next test to run attempting to equalise the time spent in each test
case.
This makes it reasonable to …
> stbt batch run: Add --shuffle option

- stbt-batch.d/run.py
- tests/test-stbt-batch.sh
`stbt batch run --shuffle` was failing with
TypeError: unhashable type: 'list'
This was not caught by the unit-tests because they don't use realistic test functions/arguments.
Before this commit each test case was a Python list which cannot be used as a key in a dictionary.  Now they are tuples so the dictionary of test-case to time-spent is now valid.
> stbt batch run: Fix and test `--shuffle` option

- _stbt/pylint_plugin.py
- docs/release-notes.md
- tests/test-stbt-lint.sh
...plus some minor fixes.
Forgetting the `assert` before `wait_until` has bitten me several times already in testcases I've written.
Note that this breaks compatibility with pylint < 1.0 (see the first commit for details). I think it's worth it. On Travis we've been installing a newer pylint from PyPI since d4a450c.
TODO:
> stbt lint: Check missing `assert` before `wait_until`

- _stbt/core.py
- docs/release-notes.md
This is similar to `Region.extend`, but it takes absolute coordinates
within the image instead of adjusting by a relative number of pixels.
It just delegates to the private `namedtuple._replace` method (`Region`
is a subclass of `namedtuple`). We have found it quite useful in some
of the test cases we write, and this saves us from having to use a
private method.
TODO:
> New API stbt.Region.replace

- stbt-batch.d/run-one
...if the previous test took <1s to run.
You're unlikely to ever see this issue in real usage, but it shows up
from time to time in stb-tester's selftests.
> stbt batch run: Avoid directory name clashes

- _stbt/core.py
I tried `nosetests --match "^_?test_"` and
`nosetests --match "^test_|^_test_"` but neither of them actually ran
these tests.
This does make the unit tests look like public functions, but the new
naming is consistent with the unit tests in all our other python files
and `_stbt.core` isn't a public module anyway.
> _stbt.core: Rename unit tests so that they get run in `make check`

- _stbt/core.py
- docs/release-notes.md
- tests/test_ocr.py
My debian testing machine now has tesseract 3.04 and these changes were required to get `match_text` working again.
**TODO:**
> ocr: Fix compatibility with tesseract 3.04

- _stbt/core.py
- docs/release-notes.md
- stbt-run
- stbt/__init__.py
- tests/test-stbt-py.sh
- tests/test-stbt-run.sh
stbt-run knows that a test has failed/errored if the test script raises an exception.  When `wait_for_match`, `wait_for_motion`, etc. fail they attach the frame that caused the failure to the exception that they raise.  stbt-run is expecting this so can save the exception for later inspection and debugging.
However: if users are using the more modern style of:
assert wait_until(lambda: match(...))
then the exception is raised by the assert, which has no knowledge of the frame that caused the assert.  In this case `stbt batch run` will grab a screenshot of whatever happens to be on screen when the test finishes.  This screenshot often doesn't exhibit the issue that caused the test to fail/error in the first place.
This commit makes the assumption that the last frame that the test script …
> stbt-run: Save last used frame on failure as screenshot.png

- _stbt/core.py
- _stbt/gst_hacks.py
- docs/release-notes.md
Preventing stb-tester from working on Ubuntu >= 14.04 and Fedora >= 21.
`map_gst_sample` was failing with:
Traceback(most recent call last):
File"/usr/libexec/stbt/stbt/__init__.py", line 1920, in on_new_sample
self.push_sample(sample)
File"/usr/libexec/stbt/stbt/__init__.py", line 1984, in push_sample
with _numpy_from_sample(sample)as img:
File"/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
returnself.gen.next()
File"/usr/libexec/stbt/stbt/__init__.py", line 1708, in _numpy_from_sample
with map_gst_buffer(sample.get_buffer(), flags) as buf:
File"/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
return self.gen.next()
File"/usr/libexec/stbt/_stbt/gst_hacks.py", line 47, in map_gst_buffer
"Writable array requested but buffer is not writeable")
ValueError: Writable …
> Work around regression in PyGObject 3.13

- Makefile
This is a small help as I was building stb-tester on my new laptop.  Now when `make enable_stbt_camera=yes` fails it prints:
Please install packages gstreamer-1.0 gstreamer-app-1.0 gstreamer-video-1.0 opencv orc-0.4
Try apt install libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libopencv-dev liborc-0.4-dev
Makefile:362: recipe for target 'stbt-camera.d/gst/stbt-gst-plugins.so' failed
make: *** [stbt-camera.d/gst/stbt-gst-plugins.so] Error 1
Which saves some time working out which debian packages provide the given pkg-config packages.
> Makefile: List debian/ubuntu packages that are missing

- .travis.yml
Travis started presenting an apt-get prompt, then timing out after 10
minutes of inactivity. Presumably they've changed their configuration
so we need to specify noninteractive mode ourselves.
> .travis.yml: Force apt to behave non-interactively

- _stbt/core.py
- tests/test_match.py
This was raising "IndexError: tuple index out of range" instead of the
desired "ValueError: Template image must be 3 channel BGR".
Fixes #310.
> stbt.match: Fix error message for greyscale images

- _stbt/core.py
Some refactorings I made while working on dual camera support so we can have two `DeviceUnderTest` objects at the same time.
This should help towards librification (#297) too.
> Mainloop handling refactoring

- _stbt/core.py
`functools.partial` creates `partial` objects that behave like a function.
However, unlike a function, they do not have a `__name__` attribute created
automatically[1]. This results in `_callable_description` raising an
`AttributeError` if `callable_` is a partial object.
This commit adds support for `functools.partial` objects in
`_callable_description`.
[1] https://docs.python.org/2/library/functools.html#partial-objects
> core: Support functools.partial objects in _callable_description

- .gitignore
- CONTRIBUTING.md
- Makefile
- extra/debian/Dockerfile.in
- extra/debian/ubuntu-shell.sh
While trying to publish ppa packages for Ubuntu 15.04 and 15.10, I've run across an issue that caused `extra/debian/build-source-package.sh` to fail: Somewhere between Ubuntu 14.04 and 15.04, `dpkg` defaults to creating `.tar.xz` files instead of `.tar.gz` files, but our script expected the latter.
This pull request adds a script to build the packages in a docker container (Ubuntu 14.04) to avoid such incompatibilities. Similar to what we already have for building Fedora packages.
TODO:
> Debian packaging fixes

- _stbt/core.py
- _stbt/gst_hacks.py
- _stbt/gst_utils.py
- stbt-camera.d/stbt-camera-calibrate.py
- stbt-camera.d/stbt-camera-validate.py
- tests/fake-video-src.py
At
```py
from gi.repository import Gst
```
the warning
```
PyGIWarning: Gst was imported without specifying a version first. Use
gi.require_version('Gst', '1.0') before import to ensure that the
right version gets loaded.
```
is printed to standard error using gi 3.18.2 (GStreamer 1.6.2).
Add `require_version` before the import to avoid the warning message.
> Require the right gi module versions before importing them to avoid warning messages

- Makefile
- _stbt/core.py
- docs/release-notes.md
This extends the fix from #319  so that it also works with nested `functools.partial` objects.
> Support recursive functools.partial objects in _callable_description

- stbt-batch.d/run-one
- stbt-batch.d/run.py
- tests/test-stbt-batch.sh
Previously we generate an HTML report before each testrun (so that the
report shows a "running..." row for the current test) and again after
the testrun (to update that row with the test's result). This report
generation gets slower as you have more results because it scans all the
results in the output directory each time.
If you have your own reporting system (such as the stb-tester ONE's
database-backed results system), this report generation is superfluous
and only slows things down.
Apart from the "index.html" inside the testrun directory and the
"index.html" one directory above it (at the root of the output
directory), no other files are affected. That is, the result format on
disk hasn't changed.
> stbt batch run: Add --no-html-report option

- stbt-batch.d/run-one
- tests/test-stbt-batch.sh
In the results view you can search by test-pack sha, so this will allow
you to search by the complete sha.
`--abbrev=40` shows the full 40-character sha instead of abbreviating it
to the shortest unambiguous prefix (unambiguous at the time that `git
describe` was run; as more commits are added it might have become
ambiguous).
`--long` shows the sha even if the head exactly matches a tag.
I considered changing this to `git rev-parse HEAD` but then we'd lose
the "dirty" information.
> stbt batch run: Store full test-pack sha in `git-commit-sha` artifact

- docs/release-notes.md
- stbt-batch.d/report
- tests/test-stbt-batch.sh
The failure was at line 65 of `stbt-batch.d/report`:
61: for resultsdir in $(
62:   for rundir in "$@"; do dirname "$(abspath "$rundir")"; done | sort | uniq)
63: do
64:   (
65:     cd "$resultsdir" || die "Invalid directory '$resultsdir'"
If you used `stbt batch -o 'my results'` it would fail with:
> report: error: Invalid directory '/path/to/my'
> report: error: Invalid directory 'results'
`stbt batch run` would continue to run the tests, but no HTML report
would be generated.
> stbt batch: Fix report generation when output directory name has spaces

- _stbt/core.py
- tests/test-match.sh
- tests/test-motion.sh
...in calls to `match`, `wait_for_match`, etc.
Before, this would show an absolute path from wherever the tests were
run, for example if you had the code `match("images/abc.png")` and you
ran it with `stbt batch -o /results` it would say "No such template
file: /results/2015-02-11_17.29.03/images/abc.png". Now it says "No such
template file: images/abc.png".
> core: Fix path in error message if template image not found

- tests/test_set_config.py
As far as I know this works correctly, but the tests wouldn't have told
us otherwise.
> tests: Fix `set_config` tests

- _stbt/core.py
On my machine with numpy 1.10.4 the `wait_for_motion` tests were failing
with:
/usr/lib/python2.7/dist-packages/nose/case.py line 197 in runTest
self.test(*self.arg)
.../_stbt/core.py line 2385 in test_wait_for_motion_half_motion_int
dut.wait_for_motion(consecutive_frames=2)
.../_stbt/core.py line 827 in wait_for_motion
for res in self.detect_motion(timeout_secs, noise_threshold, mask):
.../_stbt/core.py line 736 in detect_motion
dtype=numpy.uint8),
TypeError: Cannot cast ufunc multiply input from dtype('int64') to dtype('uint8') with casting rule 'same_kind'
This is due to a change to the default casting rule in 1.10.  The
[release notes] say:
> **Default casting rule change**
>
> Default casting for inplace operations has changed to `'same_kind'`. …
> Fix wait_for_motion visualisation with recent numpy

- tests/test-stbt-py.sh
This is another fix in the vein of e40ea49.  Without this change the
`test_template_annotation_with_ndarray_template` test would hang
indefinitely with numpy 1.10.  This is due to a change to the default
casting rule.  The [release notes] say:
> **Default casting rule change**
>
> Default casting for inplace operations has changed to `'same_kind'`.
[release notes]: https://github.com/numpy/numpy/blob/master/doc/release/1.10.0-notes.rst#default-casting-rule-change
> Tests: Fix make check with numpy 1.10

- stbt_virtual_stb.py
- tests/test-virtual-stb.sh
When launching stbt run from a different directory to which `stbt virtual-stb` was launched.
> stbt virtual-stb: Fix relative path given to --x-keymap argument

- Makefile
- _stbt/core.py
- _stbt/gst_utils.py
- _stbt/logging.py
- stbt-camera.d/stbt_camera_calibrate.py
- stbt-camera.d/stbt_camera_validate.py
- tests/test-stbt-py.sh
Instead of writing debug images to disk directly, `match`, `detect_motion` and `is_screen_black` register the debug images with an instance of `ImageLogger`. Helper functions like `_find_match` are injected the `ImageLogger` instance (this is the observer pattern).
This is better because previously `_log_image` (which wrote images to disk) and `_log_image_descriptions` (which wrote an html file) communicated with each other via the filesystem -- `_log_image_descriptions` would list the files on disk to determine how many levels of pyramid-matching had happened. This would create incorrect html output if a previous invocation of `stbt run` had created 3 levels of debug screenshots in `stbt-debug/detect_match/00001/` but the current invocation had only created 1 level (because no match was …
> Refactor image debug logging to use ImageLogger class

- tests/vstb-example-html5/tests/rotate.py
test_that_virtual_stb_configures_stb_tester_for_testing_virtual_stbs fails
intermittently on Travis because sometimes chrome takes longer than 10s to
start-up.  This causes the test to fail with:
> MatchTimeout: Didn't find match for '.../stb-tester-350px.png' within 10
> seconds
This commit should fix that issue.
TODO:
> Fix virtual-stb intermittant test-failure on Travis

- extra/fedora/stb-tester.spec.in
They have been broken since virtual-stb was introduced in 9548626.  In a
previous version of that patchset there was a stbt-virtual-stb.d, but that
was gone by the time it reached master.
> Fix building Fedora packages

- Makefile
- docs/release-notes.md
- stbt-match
- stbt.sh.in
- tests/test-match.sh
- tests/test-stbt-match.sh
For consistency with the Python API "stbt.match". I've been trying to
remove the wording "templatematch" from our public APIs as it is the
name of the OpenCV function we use in the first pass of our matching
algorithm; as such it is an implementation detail. The argument names to
`stbt.match`, `stbt.wait_for_match` etc are "image" (not "template") and
in prose we call this a "reference image" rather than a "template".
For backwards compatibility we keep "stbt templatematch" as an alias.
> Rename "stbt templatematch" command to "stbt match"

- stbt/__init__.py
- stbt_auto_selftest.py
- tests/auto-selftest-example-test-pack/selftest/auto_selftest/tests/example_selftest.py
- tests/auto-selftest-example-test-pack/selftest/auto_selftest/tests/subdir/subsubdir/subdir_example_selftest.py
- tests/auto-selftest-example-test-pack/selftest/auto_selftest/tests/unicode_example_selftest.py
In the future I want to make `stbt.get_frame()` return an immutable image.
This way we will be able to reduce copying of data by providing numpy
arrays backed by the original `Gst.Sample`s.  This will be particularly
important for better and more efficient handling of 4K video.
This commit anticipates that change by exercising user's `FrameObject`s
with read-only buffers.  This is good because it makes a future change to
the behaviour of `get_frame()` less likely to break user-scripts.  This is
a non-breaking change itself as `FrameObject` has yet to be released.
> FrameObject: Anticipate stbt.get_frame returning a read-only image

- tests/test-virtual-stb.sh
Fedora doesn't package chromium-browser.
> tests: virtual-stb: Skip tests if chromium-browser isn't installed

- stbt.sh.in
Now that we have added caching and we don't plan to change the output
format.
I'm raising this now so that I can add it to the v25 milestone so we don't forget it.
**TODO:**
> stbt.sh.in: stbt auto-selftest no longer requires "--with-experimental"

- stbt-control
- tests/test-stbt-control.sh
test_stbt_control_as_stbt_record_control_recorder__explicit_keymap was
failing with "Unable to print keymap because the terminal is too small"
when run on my PC (but not on Travis) because the test gives
`stbt control` an absolute path ($testdir/stbt-control.keymap) which on
my PC was longer than the 80-column terminal we use during the test.
The fix is to truncate the keymap filename if it's longer than the terminal width.
I've also fixed a bug in the `keymap_fits_terminal` calculation.
> stbt control: Truncate keymap filename in interactive mode

- tests/test-camera.sh
Some tests would only call `stop_fake_video_src` if the test passed;
others wouldn't call it at all.
This fixes https://github.com/stb-tester/stb-tester/issues/237
(stbt-camera selftests leave behind a lot of processes).
> tests: Fix teardown of stbt-camera test infrastructure

- _stbt/core.py
- docs/release-notes.md
- tests/test_ocr.py
This makes MatchResult values more convenient to use in auto-selftests.
I've added a `__repr__` to MatchParameters for consistency. All other classes either have a `__repr__` already, or they derive from namedtuple which provides an appropriate `__repr__` implementation.
I made a few other changes for consistency:
* Use %r instead of %s where appropriate (because this is `__repr__` after all) although in most cases the output is the same.
* `stbt.Region` had different output for `str(region)` vs. `repr(region)`: The former printed width & height whereas the latter printed right & bottom. Now both print ~~width & height~~ right & bottom (the repr can't use width & height because those are ambiguous if x or y are -inf).
TODO:
> Python API: Add __repr__ for stbt.MatchResult etc

- _stbt/imgproc_cache.py
...instead of the average. This is to fix false positives on Travis.
The minimum gives a lower bound for how fast the operation is. Higher
values will be caused by other processes competing for CPU time, which
happens especially on Travis.
TODO:
```
diff --git a/Makefile b/Makefile
index 5f0156f..033fdab 100644
--- a/Makefile
+++ b/Makefile
@@ -157,7 +157,13 @@ PYTHON_FILES = $(shell (git ls-files '*.py' && \
| grep -v '^vendor/' \
| sort | uniq | grep -v tests/webminspector)
-check: check-pylint check-nosetests check-integrationtests check-bashcompletion
+check:  # Don't merge this
+       for i in `seq 20`; do \
+         PYTHONPATH=$$PWD NOSE_REDNOSE=1 \
+         nosetests --with-doctest -v --match "^test_" \
+           --doctest-options=+ELLIPSIS \
+ …
```
> _stbt.imgproc_cache unit tests: Take the minimum time of 10 executions

- _stbt/core.py
- docs/release-notes.md
- tests/test-motion.sh
Broken out of #364.
They now all derive from object and all implement `__nonzero__`.  This will make it easier to extend them in the future in a backwards-compatible way (although this is a weakly backwards-incompatible change).
> Result object consistency

- _stbt/core.py
...if confirm_method="none".
Previously the generated html would show a table for the second pass,
full of broken links to images that didn't exist. Now it only shows the
table if confirm_method isn't "none".
> `match` debug image logging: Don't show second pass

- _stbt/core.py
- _stbt/gst_hacks.py
- _stbt/gst_utils.py
- _stbt/imgproc_cache.py
- _stbt/logging.py
- docs/release-notes.md
- extra/pylint.conf
- stbt-camera.d/stbt_camera_calibrate.py
- stbt-camera.d/stbt_camera_validate.py
- tests/test-match.sh
We were previously passing around `Gst.Sample`s because:
* There are timestamp metadata attached to them
* It was easier to handle lifetime management of the buffers, specifically WRT calling `gst_buffer_unmap`
These commits create a new numpy array type and a new backing store to solve each of those problems respectively.
Now this is done:
* We now no longer need to put `numpy_from_sample` everywhere.
* It opens the door to reducing copying, in the future we will be able to give clients these frames directly
* We have a place to attach arbitrary extra metadata to frames
I've implemented this for the last point.  I'll be needing that for #364.
TODO:
> Refactor: Hide `Gst.Sample` in `_Display` for simplicity

- _stbt/core.py
- _stbt/gst_utils.py
- docs/release-notes.md
- extra/pylint.conf
- stbt-run
- stbt/__init__.py
- tests/run-performance-test.sh
- tests/test-match.sh
- tests/test-motion.sh
- tests/test-stbt-py.sh
- tests/test_ocr.py
The timestamps we currently provide are the PTS data attached to the
`Gst.Sample`s pulled from the source pipeline.  In practice with v4l2src
this will have tended to roughly be the time from the start of the test or
the last pipeline restart.  It could be some other number depending on the
source pipeline used.   It is only useful for comparing the time
difference between two frames.
This commit introduces `sample.realtime_timestamp` for each pulled frame.
This is the time since the unix epoch in seconds as a float.  This can be
used to compare the time of a frame against:
* The current time (for debugging)
* Other events that happen on the system such as IR presses for more-precise latency measurements
* Other events that occur in the world such as remote server timestamps or for …
> Realtime timestamps

- _stbt/core.py
- docs/release-notes.md
- tests/test_ocr.py
The `__repr__` of `TextMatchResult` was raising an `IndexError` if
`match_text` was given a single-channel (black-and-white or greyscale)
image. This means that you couldn't do custom thresholding before
running the image through `match_text`. This was the stack trace:
[...]
_stbt/core.py line 1036 in match_text
debug("match_text: Match found: %s" % str(result))
_stbt/core.py line 612 in __repr__
self.frame.shape[2]),
IndexError: tuple index out of range
Note that I have also changed `MatchResult.__repr__` for consistency,
but `match` probably needs other changes too before it can support
single-channel images.
> stbt.match_text: Fix exception for single-channel images

- .gitignore
- .travis.yml
- Makefile
- _stbt/control.py
- _stbt/core.py
- _stbt/imgproc_cache.py
- pytest.ini
- stbt_auto_selftest.py
- tests/test-stbt-auto-selftest.sh
- tests/test_ocr.py
- tests/test_set_config.py
...to run our Python unit tests & doctests.
Pytest is a drop-in replacement for nose, and it has some advanced
features that I want to take advantage of in future commits, such as
test parametrization[1] and fixtures[2]. We will also benefit
immediately from pytest's cleaner output (it captures stderr as well as
stdout, so we don't have stderr output from stbt intermingled with the
py.test output) and pytest's advanced assert introspection[3].
[1]: http://doc.pytest.org/en/latest/parametrize.html
[2]: http://doc.pytest.org/en/latest/fixture.html
[3]: http://doc.pytest.org/en/latest/assert.html
> make check: Use pytest instead of nose

- Makefile
- _stbt/control.py
- docs/release-notes.md
- docs/stbt.1.rst
- stbt.sh.in
- stbt_control_relay.py
- tests/test_stbt_control_relay.py
`stbt control-relay` allows you to use any stbt remote control using the lirc socket protocol. This for example allows you to control a roku via its HTTP REST API using `irsend`.
> Add stbt control-relay

- stbt-completion
- stbt_auto_selftest.py
- tests/test-stbt-auto-selftest.sh
Even with our caching, running `stbt auto-selftest generate` on a large
test-pack can take several seconds. When you're iterating on a single
FrameObject it is useful to re-generate the selftests for just the file
you're working on.
Even with a small test-pack this reduces the run-time from 4 seconds to
1 second (when regenerating a single file).
> stbt auto-selftest generate: Accept optional source filenames

- .travis.yml
- Makefile
- _stbt/control.py
- _stbt/control_gpl.py
- docs/release-notes.md
- docs/stbt.1.rst
- extra/debian/control
- extra/debian/copyright
- extra/debian/rules
- extra/fedora/stb-tester.spec.in
- extra/pylint.conf
This is an implementation of #365.  This implementation is based on the work by @danielandersson in #378, but has been fairly heavily modified and reworked such that it's mergable into stb-tester proper.
HdmiCecControl: Implemented CEC support using libCEC
In combination with a USB-CEC adaptor this allows stb-tester to send
keypresses to devices over HDMI-CEC.  This is useful for testing devices
which don't have an IR input like the Sony PlayStation 4.
The URI is of the form:
```
hdmi-cec:[<device>]:[<source>]:[<destination>]
```
If device is not specified then any available CEC adapter will be used.
Similar to the keymapping for Roku, a map is used to lookup the CEC
commands.  We raise `UnknownKeyError` if it's not one we've heard of.  The
list of keys is from http://www.cec-o-matic.com …
> Hdmi cec control

- .gitignore
- Makefile
- _stbt/logging.py
- stbt-control-relay.in
- stbt_control_relay.py
- tests/test_stbt_control_relay.py
To make it easier to use without a dependency on the rest of stbt - for example for running a running a CEC control on a Raspberry Pi, or X11 on a remote PC.
I could have built a debian package for this but I don't think it's worth it.
> Install stbt control relay

- _stbt/control.py
- stbt-completion
This was a YouView-specific TCP-based remote control that YouView never
got around to releasing; I don't think even they use it any more.
> _stbt/control.py: Remove VirtualRemote implementation

- _stbt/logging.py
- stbt_control_relay.py
So that we can see debug output from each of the remote-control
implementations that are sending output.
Also require at last 1 output control to be specified.
> stbt-control-relay: Add --verbose parameter

- stbt-control
`stbt control` raises the error "Unable to print keymap because the
terminal is too small" if any of the printed lines is longer than the
width of the terminal. If the remote control URI is very long then it
is becoming difficult to launch the app on small screens. (The terminal
has to be made full screen and/or the font size has to be decreased.)
> stbt-control: Truncate long remote control URI to 80 characters

- irnetbox-proxy
After the service had terminated due to a dropped connection from
the irnetbox, restarting it was failing for several minutes with:
irnetbox-proxy: Traceback (most recent call last):
irnetbox-proxy: File "/usr/local/bin/irnetbox-proxy", line 225, in connect
irnetbox-proxy: self.listen_sock.bind(self.listen_addr)
irnetbox-proxy: File "/usr/lib64/python2.7/socket.py", line 224, in meth
irnetbox-proxy: return getattr(self._sock,name)(*args)
irnetbox-proxy: error: [Errno 98] Address already in use
irnetbox-proxy: Could not bind to local address
because the listening socket was left in TIME_WAIT state.  Set
the SO_REUSEADDR option on the socket to avoid this.
> irnetbox-proxy: set SO_REUSEADDR on listening socket

- _stbt/core.py
- docs/release-notes.md
- extra/pylint.sh
- stbt/__init__.py
- tests/test_ocr.py
The current behaviour is to ignore case. With this parameter at least we
can disable this behaviour if we need to.
Note that none of the ligatures in `_ocr_transtab` (like ﬃ -> ffi) exist
in uppercase versions. There *are* other ligatures that do have
uppercase & lowercase versions (œ -> oe and Œ -> OE) but they aren't in
`_ocr_transtab` and adding them is outside the scope of this commit,
as I haven't seen them in the wild and finding some test cases would
take some time I don't have right now.
> stbt.match_text: Add `case_sensitive` parameter

- _stbt/control.py
- docs/release-notes.md
- docs/stbt.1.rst
- tests/test-stbt-run.sh
It raises `RuntimeError` when the test script calls `stbt.press`.
If you don't want to use any of the built-in remote controls, this
allows you to catch unintended uses of `stbt.press` in your test script,
which would be silently ignored if you used the `none` remote control.
> _stbt/control.py: Add "error" remote control 

- docs/release-notes.md
- stbt.conf
- tests/test-stbt-run.sh
If your test calls `stbt.press` but you haven't configured a remote
control, it should fail noisily instead of silently swallowing the
keypress.
> Change the default remote control to "error"

- _stbt/power.py
The ATEN MIB is using 1.3.6.1.4.1.21317.1.3.2.2.2.2.10 for
`outletConfigTable`, so on models with more than 8 ports `outlet9Status`
and up (at least up to 36 currently) are offset by 2.
> power: fix ATEN oid for ports above 8

- tests/vstb-example-html5/virtual-stb/index.html
`keyIdentifier` is non-standard, deprecated, and it has been removed
from chromium, which is causing our `stbt virtual-stb` selftests to
fail. See
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyIdentifier
> virtual-stb selftests: Use KeyboardEvent.key instead of .keyIdentifier

- _stbt/core.py
- stbt/__init__.py
press_until_match does not take region parameter #423.
I have tested these changes locally and they do not seem to break anything.
> Patch 1 for Issue #423

- _stbt/config.py
- stbt-config
Importing `stbt` imports a whole bunch of other libraries.  This can even
take more than 1s.  With this change we only import `config.py` which
in-turn only depends on the Python standard library.  This is a lot faster.
`stbt batch run-one` calls `stbt config` 3 times or more for every test
run.  In my testing this change can save up to 5s per test run.
This tiny unexpected change demonstrates the value in profiling to work
out where the time is being spent before optimising.
> Optimisation: Don't import stbt in stbt config

- _stbt/core.py
- docs/release-notes.md
- tests/test_ocr.py
This was added for backwards compatibility in v0.21 (two and a half
years ago) but since then it has printed a warning that this change
would be made eventually.
This is consistent with `stbt.match_text`. In fact my motivation for
making this change is that the difference in behaviour caused me some
confusion when I was writing a test for the recent `text_color` pull
request. It's also consistent with the output of `Region.intersect`
which means that it's safe to pass regions created from
`Region.intersect` into `stbt.ocr`.
> stbt.ocr: Passing region=None means no region, not Region.ALL

- stbt_control_relay.py
- tests/test_stbt_control_relay.py
This will provide better integration with systemd so we can
stop or restart the relay without losing events.
TODO:
> stbt control relay: Add support for systemd socket passing

- _stbt/core.py
- extra/pylint.conf
- tests/test-virtual-stb.sh
- tests/test_core.py
If `stable_secs` is specified, wait_until should return the first stable
value. This is similar to how `wait_for_motion` reports the timestamp of
the first frame where motion was detected, even when you've asked to
validate continuous motion for several frames.
This allows uses like waiting for a selection to finish moving, and then
report how long the animation took.
**TODO:**
> stbt.wait_until: Return the first stable value, not the last

- _stbt/core.py
- docs/release-notes.md
- tests/test-match.sh
- tests/test_core.py
> Fix stbt.MatchResult and wait_until's stable_secs

- stbt-batch.d/run-one
- stbt-run
- tests/test-stbt-py.sh
- tests/test-stbt-run.sh
stbt batch run wants a JPG thumbnail of the system under test at the end
of a test run.  Previously it would spawn an additional python instance
after the test run, load the PNG screenshot and then save it as a jpeg.
If the test run succeeded it would even spawn yet another stbt run just
to create a screenshot.png before deleting it after converting it to JPG.
This commit tidies this up.  stbt-run is responsible for creating all
screenshots and thumbnails as it has access to the uncompressed source
screenshot to start with.  This can save 1s for each test run by
`stbt batch`.
> stbt-batch: Performance improvements: Record screenshots in stbt-run

- _stbt/core.py
`_Annotation.from_result` uses the result's "time" attr (not
"timestamp") since commit 9c110be "core: Use wall-clock timestamp
everywhere instead of pts".
> _stbt.core.SinkPipeline.draw: Fix check for "time" attr

- tests/test-virtual-stb.sh
- tests/vstb-example-html5/run.sh
They've started failing since the latest Chromium release (59.0.3071.109). I disabled the tests temporarily in commit 1e490e5. 
Using `stbt tv` to debug the running virtual-stb shows a blank white page. Loading the same page in chromium-browser directly works fine.
```
./stbt_virtual_stb.py run tests/vstb-example-html5/run.sh &
./stbt-tv
```
vs.
```
chromium-browser --no-sandbox --app=file://`pwd`/tests/vstb-example-html5/virtual-stb/index.html
```
> Fix virtual-stb with Chrome 59

- tests/test-stbt-py.sh
Fixes the following self-test error:
stbt-run: OCR in region Region(...) read '16:01 :O6.86'.
ValueError: invalid literal for int() with base 10: 'O6'
> test_clock_visualisation: Fix OCR misread

- Makefile
- extra/pylint.sh
...by passing all python files to a single pylint process, instead of
one at a time. This way pylint doesn't have to re-load every imported
file (recursively) from scratch every time.
On my laptop this cuts the runtime of `make check-pylint` by 30 seconds
(from 53 seconds to 23 seconds) even though I was using 4 cores before
and now only 1 core. On Travis this saves about 70 seconds (the gains
are larger as there is less concurrency available on Travis).
Curiously this caused pylint to flag a few new problems in the
auto-generated files in `tests/auto-selftest-example-test-pack/selftest`
so I've added those to the list of excluded files.
> make check-pylint: Speed up pylint

- _stbt/core.py
- docs/release-notes.md
- stbt.conf
- stbt/__init__.py
- tests/stbt.conf
- tests/test_ocr.py
To avoid specifying it in every single call to `stbt.ocr`.
> stbt.ocr: Make the default value of `lang` configurable

- _stbt/config.py
- _stbt/core.py
- docs/release-notes.md
- stbt-camera.d/stbt_camera_calibrate.py
- stbt-record
- stbt-run
- stbt.conf
- stbt/__init__.py
- tests/stbt.conf
- tests/test-stbt-py.sh
We added this in 52579fa to work around a deadlock bug in decklinksrc.
This caused additional problems:
* That commit itself had a race, fixed in cc125fb;
* Non-live sources (e.g. filesrc for self-tests) now would take 10
seconds to teardown, presumably because the EOS was caught behind a
long queue of buffers. We tried to fix this in fadfe6e and e051ba8
but we reverted those two commits (in 8f1b48c and 8ee2ab5) because it
caused intermittent long teardown in live v4l sources.
Now I've just made it configurable, and we don't send the EOS at all by
default.
> core.py: EOS on source pipeline teardown is configurable (off by default)

- docs/release-notes.md
- stbt.conf
This matches what the documentation says, and it's the best practice to
avoid confusing the device-under-test with infrared signals that are too
close together.
> stbt.conf: Change default interpress_delay_secs to 0.3

- _stbt/control_gpl.py
This allows you to get to the reserved numbers (maybe some manufacturers
have implemented some of them) or to implement your own string->keycode
mapping.
> CEC control: Allow specifying CEC numerical codes directly

- Makefile
- _stbt/camera/chessboard.py
- _stbt/core.py
- _stbt/cv2_compat.py
- docs/release-notes.md
- stbt-run
- stbt/android.py
- tests/test_match.py
Debian testing now has OpenCV 3 so I need this change to make stbt development convenient on my PC.
This isn't necessarily complete, but it does help to get a bunch of more tests to pass.
TODO:
Further Work:
- Set up Travis to build a configuration with OpenCV 3 too.  We can't call it supported until we've got regular testing happening. Perhaps this can wait until Ubuntu 18.04 is released?
> OpenCV 3 Compatibility

- _stbt/core.py
Also add some characterization tests to avoid similar regressions in future.
> stbt.match debug html: Fix "didn't match" in title

- _stbt/core.py
- docs/release-notes.md
- tests/test_frame_object.py
Previously `is_visible` could only call private properties of the
FrameObject. If you tried to call a *public* property from `is_visible`,
you would get "RuntimeError: maximum recursion depth exceeded". This was
a side-effect of the FrameObject design that public properties should
return `None` if the FrameObject isn't visible. To work around this you
had to add a private property that was used by both `is_visible` and the
corresponding public property.
Now each FrameObject instance knows if it's inside a call to
`is_visible`, so that you can call public properties.
> stbt.FrameObject: `is_visible` can call other public properties

- _stbt/core.py
- docs/release-notes.md
- stbt/__init__.py
- tests/test_ocr.py
Stb-tester upsamples the image before passing it to tesseract (since v0.20 in 2014). For details see https://stb-tester.com/blog/2014/04/14/improving-ocr-accuracy
With this parameter you can *disable* that behaviour. This is useful if you want to do your own pre-processing before calling `stbt.ocr`. For example this would have made it possible to implement `text_color` in your test-pack without modifying stb-tester.
> stbt.ocr & stbt.match_text: Add upsample parameter to disable upsampling

- tests/test-soak.sh
It takes 30 minutes to run so it doesn't run on Travis. Run it manually
with:
STBT_RUN_SOAK_TESTS=1 tests/run-tests.sh \
test_long_running_stbt_run_process_for_memory_leaks
I'm not expecting to find a memory leak, just being thorough.
> selftests: Add soak test for memory leaks

- _stbt/stbt_run.py
- tests/test-stbt-batch.sh
- tests/test-stbt-completion.sh
- tests/test_functions.py
...even if the test-script calls `os.chdir`.
Note: this isn't a supported way of running `stbt batch`, but we have seen it happen in practice and it's an easy fix.
> Ensure that thumbnail and screenshot are written to results dir

- .travis.yml
- extra/debian/control
- tests/test-stbt-batch.sh
- tests/test-stbt-completion.sh
- tests/test_functions.py
`stbt batch run` uses gdb to generate a backtrace.log file if a core
file (core dump) is present after the test-run. This is useful because
it ensures that gdb is run against the same libraries that the core file
was generated from. `stbt batch` has had this functionality since day
one, but we've never specified gdb as a dependency in the debian
packages. Without gdb installed, backtrace.log says "gdb: command not
found" instead of the backtrace.
> debian packages: Install gdb (`stbt batch run` dependency)

- _stbt/core.py
- tests/test_frame_object.py
See 78478e02a1 and the discussion on #483 for the background behind this
thread-local.
Traceback:
...
File ".../stb-tester/_stbt/core.py", line 1727, in __repr__
args = ", ".join(("%s=%r" % x) for x in self._iter_attrs())
File ".../stb-tester/_stbt/core.py", line 1727, in <genexpr>
args = ", ".join(("%s=%r" % x) for x in self._iter_attrs())
File ".../stb-tester/_stbt/core.py", line 1731, in _iter_attrs
if self:
File ".../stb-tester/_stbt/core.py", line 1739, in __nonzero__
return bool(self.is_visible)
File ".../stb-tester/_stbt/core.py", line 1660, in inner
self._FrameObject__local.in_is_visible += 1
AttributeError: 'thread._local' object has no attribute 'in_is_visible'
TODO:
> FrameObject: Fix AttributeError with multiple threads

- _stbt/state_watch.py
...it's not needed unless you pass `--save-trace` to `stbt run`.
> state_watch: Make dependency on python-lzma optional

- .gitignore
- Makefile
- _stbt/stbt.conf
- docs/release-notes.md
- tests/stbt.conf
`stbt run` will no longer show an output video window by default. This is a
better default for headless environments like stbt-docker.  You can re-enable
this by setting `global.sink_pipeline = xvimagesink sync=false` in your
`$HOME/.config/stbt/stbt.conf`
> Make stbt-run headless by default

- _stbt/core.py
GStreamer's tee can be a little funny some times when it comes to
caps negotiation and errors.  Avoid it if possible.
This will also save two threads and the associated costs.
> sink pipeline: Only tee if we have to

- _stbt/stbt_run.py
- docs/release-notes.md
- tests/test-stbt-run.sh
This provides more flexibility in how you organise your test-pack.  If you
put `__init__.py` under `tests/` you will now be able to do:
from .helpers import test_helper
Note the `.` before helpers indicating that this is a relative import.
Relative imports becomes more important when there is a file hierarchy as
you can import from a parent package:
from ..utils.helpers import test_helpers
This follows the same [behaviour from py.test][1].
[1]: https://docs.pytest.org/en/latest/goodpractices.html#test-package-name
> stbt-run: Fix relative imports within your test-pack

- _stbt/core.py
- _stbt/gst_utils.py
- docs/release-notes.md
- stbt/__init__.py
- tests/test_core.py
So that you can get the exact frame that was analysed, for more precise
performance measurements.
TODO:
> stbt.is_screen_black: Return IsScreenBlackResult instead of bool

- _stbt/control.py
- _stbt/control_gpl.py
- _stbt/core.py
- docs/release-notes.md
- stbt-control
- stbt-record
- stbt/__init__.py
- stbt_control_relay.py
- tests/fake-lircd
- tests/test-lirc.sh
- tests/test-stbt-control.sh
- tests/test_press.py
- tests/test_stbt_control_relay.py
Allows holding down a key on the remote-control for a certain duration, or (for the `stbt.pressing` context manager) while a block of code executes.
Only implemented for LIRC, Roku, and CEC controls. I haven't implemented the other controls because I don't know how, or it's impossible. I specifically know that the IRNetBox doesn't have separate keydown/keyup commands.
[lircd(8)]: http://www.lirc.org/html/lircd.html
---
**TODO**
- Does it have a time limit after which it considers the key released? No, I tested keydown "Down" and after 4 minutes it's still happily scrolling down the menu.
> Add stbt.press(hold_secs) parameter, and stbt.pressing context manager

- _stbt/core.py
- _stbt/gst_utils.py
- tests/test_motion.py
60fps is 17ms per frame, or 0.017s; having timestamps more precise than
that is misleading and distracting.
> Debug logging: Log timestamps with 3 decimal places 

- _stbt/core.py
- _stbt/gst_utils.py
- _stbt/transition.py
- docs/release-notes.md
- stbt/__init__.py
- tests/test_core.py
- tests/test_transition.py
`IsScreenBlackResult` hasn't been released yet (it was added after v28). Users don't need to construct these, and its name is horrible.
I've had to move its documentation into `is_screen_black`, where I've mimicked the formatting that Sphinx's `:ivar:` generates.
Also rename `TransitionResult` -> `TransitionStatus` -- I was a bit hasty in merging the final post-review changes of #445.
> Don't expose IsScreenBlackResult in public API 

- Makefile
- _stbt/core.py
- _stbt/gst_utils.py
- _stbt/imgutils.py
- _stbt/logging.py
- _stbt/motion.py
- _stbt/types.py
- stbt/__init__.py
- tests/test_motion.py
They are no longer members of `DeviceUnderTest` so we no-longer need to
have forwarding implementations in `stbt/__init__.py`.
I think this general model makes some sense.  The different image
processing bits are no longer bound so tightly together.  But we make a
concession to convenience - frames defaults to `stbt.frames()`.  By
introducing this impurity we maintain the convenience of the existing API.
It makes the tests cleaner too.
> Add `frames` parameter to `wait_for_motion` and `detect_motion`

- _stbt/core.py
- _stbt/motion.py
- _stbt/transition.py
- docs/release-notes.md
- stbt-camera.d/stbt_camera_calibrate.py
- stbt/__init__.py
- tests/run-performance-test.sh
- tests/test-soak.sh
- tests/test-stbt-py.sh
- tests/test_motion.py
- tests/test_transition.py
...from Iterator[(Frame, int)].
This is a breaking change, but the error will happen immediately and the
error message will be somewhat obvious: "ValueError: too many values to
unpack". Also, there should be very few uses of `stbt.frames()` in any
given test-pack.
The second field of the yielded tuple was a timestamp in
nanoseconds (GStreamer format). This has been deprecated since we added
`stbt.Frame.time` in v26, 2 years ago.
Now seems like a good time to do this because we've just added a
`frames` parameter to `detect_motion` and `wait_for_motion`. This API is
much more convenient.
> stbt.frames: Change return type to Iterator[Frame]

- _stbt/pylint_plugin.py
- stbt-lint
- tests/test-stbt-lint.sh
Typical usage should be this:
assert press_and_wait("KEY_DOWN")
not this:
press_and_wait("KEY_DOWN")
> stbt-lint: Check that return value of `press_and_wait` is used

- _stbt/control.py
- _stbt/imgutils.py
The [python-requests documentation][1] says:
> Nearly all production code should use this parameter in nearly all
> requests. Failure to do so can cause your program to hang
> indefinitely.
[1]: http://docs.python-requests.org/en/master/user/quickstart/#timeouts
> RokuHttpControl: Enforce 3 second timeout on all HTTP requests 

- _stbt/frameobject.py
- tests/test_frame_object.py
The examples are a bit excessive for a reference -- they overwhelm the
API reference in our manual as the FrameObject docs took up 5
screenfuls (now it's down to a single screenful). Instead I've linked
to worked examples elsewhere in our manual, blog, and tutorials.
I've also mentioned the relationship to Selenium's Page Objects, and
`stbt auto-selftest` for testing your Page Objects, and Stb-tester's
proprietary "Object Repository" GUI.
> FrameObject docstring: Remove examples; link to further reading

- _stbt/pylint_plugin.py
- stbt-lint
- tests/test-stbt-lint.sh
This is a common & annoying problem -- stbt-lint passes locally but
fails on your CI server (as do the actual tests!).
I've used `subprocess` instead of `dulwich` because the latter is hard
to use (the version on Ubuntu 16.04 doesn't have
`dulwich.porcelain.ls_files`) and its Apache 2.0 license isn't
compatible with LGPL v2.1.
> stbt lint: Report images that exist but aren't committed to git

- _stbt/pylint_plugin.py
- tests/test-stbt-lint.sh
Inside a FrameObject property, if you do `stbt.match("image.png")`
instead of `stbt.match("image.png", frame=self._frame)`, stbt-lint will
warn you. However it wasn't warning if you were instantiating a **class**
that takes a `frame` parameter. This is a common use-case because
sometimes we want to return a FrameObject as the result of a different
FrameObject's property. For example, a FrameObject called `Dialog`
might have a property called `button` that returns an instance of a
`Button` FrameObject class.
> stbt-lint: stbt-frame-object-missing-frame checker: Also check class constructors

- .travis.yml
- Makefile
- _stbt/control.py
- stbt-camera.d/stbt_camera_calibrate.py
You need to do `make check enable_virtual_stb=yes`.
This is because the tests screw up my X11 display when I run them
locally. Note that stbt-virtual-stb is already a separate debian
package because of all its dependencies on X11.
> make check: Don't run virtual-stb tests by default

- .circleci/config.yml
- .circleci/ubuntu1604-python2.dockerfile
- .gitignore
- .travis.yml
- Makefile
- _stbt/control.py
- _stbt/core.py
- _stbt/gst_hacks.py
- _stbt/gst_utils.py
- _stbt/irnetbox.py
- _stbt/match.py
- _stbt/ocr.py
- _stbt/stbt_run.py
- _stbt/utils.py
- irnetbox-proxy
- stbt-camera.d/stbt_camera_calibrate.py
- stbt-camera.d/stbt_camera_validate.py
- stbt-match
- tests/test-stbt-auto-selftest.sh
- tests/test_ocr.py
- tests/test_set_config.py
Unlike Travis, CircleCI makes it easy to run tests inside a docker
container. So we'll build docker images for Ubuntu 16.04 and Ubuntu
18.04 (the latter in a future commit), push them to Docker
Hub (manually, needs to be done by the Stb-tester project owners but
only when we need to install new dependencies), and then CircleCI will
pull the image from Docker Hub each time it runs the tests.
> Use CircleCI for Continuous Integration testing

- _stbt/motion.py
A common mistake is to use it directly in an `if` statement
(`if stbt.detect_motion():`) which is always true because it's a
generator object.
> stbt.detect_motion docstring: Clarify that you need to use it in a `for` loop

- _stbt/core.py
- _stbt/imgutils.py
- tests/test_match.py
This makes transparency work when you call `stbt.load_image` and pass the result to `stbt.match`, instead of passing the filename to `stbt.match`.
TODO:
> stbt.load_image: Change `flags` default value to BGR[A]

- Makefile
- extra/debian/build-source-package.sh
It turns out that we had forgotten to publish the PPA packages back in June.
> debian: Fixes for publishing to PPA from Ubuntu 18.04 build machine

- _stbt/ocr.py
With this change we interpret `$TESSDATA_PREFIX` in the same way as
tesseract when using tesseract 4.00.
For more information see cbbf873e94.
I'm using this in combination with https://github.com/tesseract-ocr/tessdata/pull/114
> ocr: Fix when `TESSDATA_PREFIX` is set on tesseract 4.00

- stbt_auto_selftest.py
Importing stbt + gstreamer bindings + opencv is slow. On Unix systems
`multiprocessing.Pool` uses `fork` so by importing stbt first, these
modules won't be imported from scratch in each subprocess. We use a
different subprocess for each Python file that we analyse.
This saves about 1 second on `tests/auto-selftest-example-test-pack`.
The improvement will be even larger on test-packs with more Python
files.
This should also make `test_auto_selftest_caching` more reliable.
> stbt auto-selftest: Pre-import stbt & dependencies for better performance

- _stbt/imgproc_cache.py
- _stbt/match.py
Here we create `roi_mask` which is used in the next iteration of the
`for` loop. In the last iteration we don't need to create a new
`roi_mask`, because it isn't used after the `for` loop.
This saves up to 1ms on my laptop.
> stbt.match: Performance optimisation: Don't threshold last matchTemplate heatmap

- _stbt/match.py
stbt.load_image already checks (see `_stbt/imgutils.py::imread`).
> stbt.match optimization: Don't check for 100% opaque mask *again*

- _stbt/match.py
- _stbt/stbt.conf
- docs/release-notes.md
- stbt-match
- tests/stbt-debug-expected-output/match/00002/index.html
- tests/stbt-debug-expected-output/match/00003/index.html
- tests/stbt-debug-expected-output/match/00004/index.html
- tests/stbt.conf
- tests/test-camera.sh
- tests/test-match.sh
- tests/test-stbt-match.sh
- tests/test-stbt-py.sh
- tests/test_stbt_debug.py
Now 0 means "less strict" and 1.0 means "completely strict". i.e. it's measuring the similarity, rather than the difference (error).
This is for consistency with the `match_threshold`. The discrepancy has caused some confusion in the past.
In all the user test-scripts that we've seen, confirm_threshold is never changed from its default values, except to set it to an absurdly high value (where the intent was really to disable the confirm pass; you can do that with `confirm_method=ConfirmMethod.NONE`).
> stbt.match: Invert the meaning of confirm_threshold

- _stbt/logging.py
- _stbt/match.py
- tests/stbt-debug-expected-output/is_screen_black/00001/index.html
- tests/stbt-debug-expected-output/is_screen_black/00002/index.html
- tests/stbt-debug-expected-output/is_screen_black/00003/index.html
- tests/stbt-debug-expected-output/is_screen_black/00004/index.html
- tests/stbt-debug-expected-output/match/00001/index.html
- tests/stbt-debug-expected-output/match/00002/index.html
- tests/stbt-debug-expected-output/match/00003/index.html
- tests/stbt-debug-expected-output/match/00004/index.html
- tests/stbt-debug-expected-output/motion/00001/index.html
- tests/stbt-debug-expected-output/motion/00002/index.html
- tests/stbt-debug-expected-output/motion/00003/index.html
- tests/stbt-debug-expected-output/motion/00004/index.html
- tests/stbt-debug-expected-output/motion/00005/index.html
- tests/stbt-debug-expected-output/motion/00006/index.html
If you were serving these generated HTML files over HTTPS, browsers
would refuse to load the CSS from an HTTP URL.
> debug html: Link to bootstrap CSS file with HTTPS 

- _stbt/sqdiff.py
`mask[mask & 1] == 255` sets *all* elements of the array to 255, unconditionally. Also, it fails if the height or width of the array is 1 (this is how I noticed): "IndexError: index 1 is out of bounds for axis 0 with size 1".
You need to index with an array of bools instead.
> test_sqdiff_c_numpy_equivalence: Fix generating mask

- _stbt/types.py
`bounding_box` is associative and commutative so there's no reason
not to.
> Region.bounding_box: Remove limit of just passing two regions

- _stbt/core.py
- _stbt/transition.py
- docs/release-notes.md
- stbt/__init__.py
- tests/test-stbt-py.sh
- tests/test_press.py
- tests/test_transition.py
A common pattern for benchmarking is:
stbt.press('KEY_XXX')
start_time = time.time()
x = wait_until(xyz)
duration = x.time - start_time
This moved the `time.time()` bits into `stbt.press` itself where it
can do a better job as it is `interpress_delay_secs` aware.
This was motivated by some changes I want to make to the transition
APIs.  When writing page objects you have to deal with transitions
between different pages.  For example a menu might know that it has
to press `'KEY_OK'` to launch the EPG, but only the EPG knows how
to wait until the EPG has finished loading.  In this case the `key`
argument to `press_and_wait` is defined by the `Menu` page object,
whereas the `mask` would be defined by `EPG`. This API is a step
towards being able to implement this as:
r = stbt.press('KEY_OK') …
> API: Add return value from `stbt.press`

- _stbt/core.py
This hides the actual warning message, and it causes the test to error
instead of passing.
Introduced in #563.
> core: Fix teardown error "not all arguments converted during string formatting"

- _stbt/transition.py
- tests/test-stbt-py.sh
Since 75fd9feb65d `press_and_wait` has failed with the exception:
...
File "test.py", line 7, in <module>
assert stbt.press_and_wait("white")
File "_stbt/transition.py", line 82, in press_and_wait
press_result = _dut.press(key)
AttributeError: 'NoneType' object has no attribute 'press'
This wasn't caught by our existing tests because each of them inject a
custom `dut` for testing and this issue was caused by not defaulting `dut`
correctly.
> press_and_wait: Fix regression

- _stbt/core.py
- _stbt/stbt.conf
- docs/stbt.1.rst
- stbt-completion
- tests/stbt.conf
- tests/test-stbt-py.sh
This was a workaround for a bug in the Hauppauge HDPVR video-capture
device, which is ancient and unreliable hardware. As far as I know,
nobody uses this setting.
Note that we *do* restart the source pipeline if we receive EOS (always,
regardless of configuration). This setting also restarted the source
pipeline on underrun (no buffers received, but without an EOS either).
> Remove "restart_source" config setting

- .circleci/config.yml
- .circleci/ubuntu1804-python3.dockerfile
- Makefile
- extra/pylint.sh
- tests/run-tests.sh
- tests/test-irnetbox.sh
- tests/test-lirc.sh
- tests/test-match.sh
- tests/test-motion.sh
- tests/test-packaging.sh
- tests/test-stbt-py.sh
- tests/test-stbt-run.sh
- tests/utils.sh
The main change here is that `make install` modifies the shebang lines upon installation, from `#!/usr/bin/python` to `#!/usr/bin/python2.7` or `#!/usr/bin/python3` depending on the value of `$python_version`.
The rest of the changes are just test infrastructure to cope with that, plus other test fixes.
> Python 3 packaging

- _stbt/core.py
If you are importing `stbt` as a library and you try to call `stbt.get_frame()` without initialising the video-capture pipeline (which is normally done by `stbt run`), you'd get the following exception:
> AttributeError: 'NoneType' object has no attribute 'get_frame'
This also happens if you're running `stbt auto-selftest` on your page objects, and you have forgotten to pass `self._frame` explicitly into any image-processing calls like `stbt.match`.
> stbt.get_frame: Improve error message if video-capture uninitialised

- _stbt/transition.py
On the Apple TV, successive frames differ by up to 3 (out of 255) on almost every pixel, in a funky multicoloured moire pattern. Here's what it looks like after enhancing the levels (remember the actual differences are <= 3 so you can't see them with the naked eye):
> stbt.press_and_wait: Ignore pixel intensity differences <= 5

- _stbt/ocr.py
The LSTM engine hallucinates text that isn't there when the input isn't long prose, so it doesn't work for typical GUI testing where we want to read menus, buttons, prices, numbers, times, etc.
> stbt.OcrMode docstring: Recommend tesseract's v3 engine

- stbt/keyboard.py
- tests/test_keyboard.py
It was always calculating the path as if it was starting again from the initial position (before it had entered any of the previous letters).
Sometimes this would work, because `navigate_to` has a loop where it double-checks that it landed where it expected, and then recalculates. Other times it might end up navigating away from the keyboard (e.g. into the search results).
This bug was introduced in commit 5756985 (keyboard: Move `page` parameter from constructor to `enter_text`). I suppose I didn't re-test against a real set-top-box after doing that change.
This bug wasn't caught by the unit tests because it was using a class that wasn't a real `stbt.FrameObject` -- in particular it didn't have the immutable behaviour of FrameObjects, so the `selection` property was updating even when …
> Keyboard.enter_text: Fix navigation after the first letter 

- stbt/keyboard.py
- tests/test_keyboard.py
This API is a little bit hard to use: In the example from the docstring, we were passing an out-of-date page object into `Keyboard.navigate_to`. So after typing the text, it was calculating the path to the "SEARCH" button from your initial state, not from the actual state (which should be the last letter in the text you've typed). This could lead it to pressing a sequence of keys that take it out of the keyboard altogether.
This fixes the example in the docstring, and we also reverse the order of arguments to give us a bit more flexibility in how we might solve this in the future without breaking the Keyboard API.
> stbt.Keyboard: Reverse order of arguments to enter_text & navigate_to

- stbt/keyboard.py
Saves you from having to define it in your test-pack.
> Add stbt.Keyboard.Selection convenience type 

- _stbt/grid.py
- stbt/__init__.py
- stbt/keyboard.py
- tests/test_grid.py
- tests/test_keyboard.py
Provides a much easier way of specifying grid-like keyboards. See `test_composing_complex_keyboards` in 1df3d7b for an example.
> Keyboard & Grid fixes

- _stbt/types.py
- tests/test_core.py
`intersect` is a `@staticmethod`, but you can still call it on an instance -- and the instance will be ignored, not considered among the arguments.
So `r1.intersect(r2)` behaves like `stbt.Region.intersect(r2)`, not like `stbt.Region.intersect(r1, r2)`.
Before v30, calling `intersect` with a single region wouldn't have been allowed because it required exactly 2 arguments; but since v30 (when we allowed an arbitrary number of arguments) this incorrect usage wouldn't cause an assertion and even `stbt lint` wouldn't catch it.
Similarly for stbt.Region.bounding_box.
---
TODO:
> Disallow calling region.intersect() on a Region instance

- _stbt/ocr.py
Tesseract 4.0's LSTM engine ignores char_whitelist.[1]
This is fixed in Tesseract 4.1 [2] but it isn't widely available
yet (it'll be in Ubuntu 19.10).
[1]: https://github.com/tesseract-ocr/tesseract/issues/751
[2]: https://github.com/tesseract-ocr/tesseract/wiki/ReleaseNotes#tesseract-release-notes-jul-07-2019---v410
> stbt.ocr docstring: Note that LSTM engine ignores char_whitelist

- stbt/keyboard.py
So that you can return `Selection(None, None)` if no selection is
detected, and callers can say `if selection:` instead of
`if selection.region:`.
> stbt.Keyboard.Selection: Implement `__bool__`

- _stbt/match.py
- _stbt/ocr.py
The behaviour of `stbt.match` changed in commit 0a4e6a1 (stbt.match: Pyramid optimisation: Ignore pixels on edge of reference image) to fix a bug where mostly-transparent images with a thin border wouldn't match (false negatives). Don't know about `stbt.ocr` but it doesn't hurt to bump that version too.
> Bump imgproc_cache version to 31

- stbt/keyboard.py
- tests/test_keyboard.py
Previously the only verification was in the while loop's condition:
`while current != target`. So if your model of the keyboard was wrong,
`navigate_to` would keep on trying to reach the target until
`navigate_timeout` was reached (default 20 seconds). Maybe this would
allow to eventually reach the key, but it can also lead to very
confusing, hard to debug, behaviour.
Now we verify that we've reached each letter in the word you're trying
to type, so we fail earlier and we provide a useful error message.
Optionally we can also verify each state in the journey from the current
selection to the target letter, by specifying
`verify_every_keypress=True`. This is slower and less human-like but
you'd only set while debugging your model.
---
TODO:
> stbt.Keyboard: Verify that you've reached the target

- _stbt/match.py
- _stbt/motion.py
- _stbt/transition.py
- _stbt/types.py
- tests/test_core.py
...in fact this will allow translating by any tuple that has x and y as the first two items.  This is helpful when dealing with items that have substructure.  For example: A carousel might have multiple items laid out in a grid:
+---------------+     +----------------+
|    Title 1    |     |    Title 2     |
|               |     |                |
| Description 1 |     | Description 2  |
| this TV show  |     | this one isn't |
| is really     |     | so interesting |
| good and      |     |                |
| exciting      |     |                |
|               |     |                |
+---------------+     +----------------+
The boxes might be given by `REGION[0]` and `REGION[1]`.  You could then
have `TITLE_REGION` and `DESCRIPTION_REGION` relative to the boxes.  To read
all the …
> Region: Allow translating one region by another one

- _stbt/control.py
- _stbt/core.py
- _stbt/grid.py
- _stbt/match.py
- _stbt/ocr.py
- _stbt/utils.py
- stbt/keyboard.py
- tests/test_keyboard.py
- tests/test_lirc_control.py
- tests/test_ocr.py
So `stbt.Keyboard` isn't broken for our customers who use Python 2.
> Backport parts of #629 to v31

- _stbt/frameobject.py
- stbt/__init__.py
A decorator that marks classes and functions so they appear in the Object
Repository.
Classes that directly derive from `stbt.FrameObject` have this decorator
applied to them automatically.  This can be used to register other classes
and functions.
These classes are extracted by static analysis, so the decorator is a noop,
returning the class unchanged.
> Add `for_object_repository` decorator

- Makefile
If you attempt to run make using clang, you would currently get an error where xxHash is being compiled because it appears clang will treat all the files as .c files. Since the .h file is still necessary in the sources, this change circumvents that error by simply filtering it out from the compilation step. 
```sh
clang: error: cannot specify -o when generating multiple output files
make: *** [_stbt/libxxhash.so] Error 1
```
See issue #632
> Filter out xxhash header file to prevent clang error

- _stbt/frameobject.py
This decorator is used for marking indirect subclasses of FrameObject,
that wouldn't be otherwise detected by Stb-tester's [Object Repository].
It doesn't make any sense to apply it to the FrameObject base class
itself.
[Object Repository]: https://stb-tester.com/manual/object-repository
> stbt.FrameObject base class: Remove @for_object_repository decorator

- _stbt/types.py
This is useful when comparing if some region is above another region,
without having to worry about getting the edges of each region exactly
right. e.g. we might have region1 detected at run-time with `stbt.match`
and region2 hard-coded in the test scripts:
is_above = region1.center.y < region2.y
If we used `region1.y < region2.y` we would get false positives if
region1 *is* at region2 (the selection is on the desired target) but the
way we calculated region1 is off by 1 pixel compared to region2.
If we used `region1.bottom < region2.y` we would get false negatives if
region1 *is* in the position immediately above region2 but, again, we
got the region off by a few pixels (or the seleted item is bigger and
overlaps surrounding items slightly).
Using the center of region1 solves both of …
> stbt.Region: Add `center` property

- setup.py
Fixes GitHub warning:
> CVE-2019-10906
> high severity
> Vulnerable versions: < 2.10.1
> Patched version: 2.10.1
>
> In Pallets Jinja before 2.10.1, str.format_map allows a sandbox escape.
Not that it's particularly relevant as any user-provided code that could
affect the Jinja output (used to generate the detailed stbt-debug html)
comes from the user's test scripts which are run outside Jinja's sandbox
already.
> setup.py: Upgrade Jinja2 dependency

- .gitignore
- Makefile
- setup.py
So that `pylint --load-plugins=stbt.pylint_plugin` will work without
further installation steps.
I have pinned the versions to match Ubuntu 18.04. The latest versions
(pylint-2.4.4 & astroid-2.3.3) fail with:
>   File "venv/lib/python3.6/site-packages/stbt/pylint_plugin.py", line 23, in <module>
>     from astroid import MANAGER, YES
> ImportError: cannot import name 'YES'
We should probably fix that at some point, but pinning these versions
will avoid problems outside our control whenever there's a new astroid
release. We've had trouble with astroid's backward compatibility before.
> setup.py: Specify pylint & astroid dependencies with pinned versions

- _stbt/control.py
- _stbt/core.py
- _stbt/imgutils.py
- tests/test_core.py
`future.utils.text_to_native_str` only works if the input is unicode. It
does this:
return unicode(t).encode(encoding)
And the `unicode(t)` is what fails.
It seems that we had tested bytes & unicode in
`test_load_image_with_unicode_filename` at some point in the past, but
not since we added `from __future__ import unicode_literals`.
Note that b"Röthlisberger" is a SyntaxError on Python 3: bytes can only
contain ASCII literal characters.
I had to do some contortions with the IOError exceptions we raise. If
you give it a unicode message on Python 2, it displays like this:
`IOError: <unprintable IOError object>`.
> stbt.load_image: Fix UnicodeDecodeError when filename is utf-8 bytes

- _stbt/config.py
Now that our customers are installing Stb-tester locally from PyPI, they'll be seeing this docstring in their IDE and mentioning man pages will be confusing.
> stbt.get_config: Update docstring to match behaviour on the Stb-tester Platform

- _stbt/cv2_compat.py
- docs/release-notes.md
This is in regards to #648. Sorry for the delay.
OpenCV4 changed the behavior of `findContours` back to returning
`(contours, hierachy)` instead of `(image, contours, hierachy)`.
However, the `cv2_compat` file is trying to find contours as the second
return value for any version of cv2 >= 3.2.0.
This is a small fix that ensures contours is still selected
on version of openCV >= 4.0.0.
> Add support for OpenCV4

- stbt/__init__.py
You'll want to see this message in the logs too, and you don't want to have to write a `stbt.debug(...)` for every `stbt.draw_text(...)` in your test.
> stbt.draw_text: Also write text to stderr

- _stbt/core.py
It should be the frame's time, not the current wall-clock time.
SinkPipeline buffers half a second of frames to give the user code
enough time to draw annotations on them before they are pushed to the
video encoder -- so these timestamps were all wrong by half a second.
> core: Fix frame timestamps drawn on output video

- _stbt/types.py
Sometimes when you've identified a selection (with stbt.match or some
other mechanism) you want to tell which row/cell it corresponds to (in a
table/grid) and it doesn't matter if the selection is slightly larger
than the cell, so you use `cell.contains(selection.region.center)`.
> stbt.Region.contains: Accept a `Position` as the argument

- stbt/pylint_plugin.py
I have started using a convention of a classmethod called
"wait_until_visible" on my Page Objects, like this:
page = Carousel.wait_until_visible(keypress)
Our pylint plugin thinks this is `stbt.wait_until` and complains:
"wait_until" argument "keypress" isn't callable.
> stbt.pylint_plugin: Fix false positive for "wait_until_..."

- _stbt/imgutils.py
- tests/test_core.py
This simplifies writing functions like this:
def my_helper(mask=None):
if mask:
mask = stbt.load_image(mask)
...such that `mask` can be a filename, or an image constructed in code
using `numpy.zeros` etc.
> stbt.load_image: Allow passing an image

- stbt/keyboard.py
I have seen the second KEY_OK be ignored when pressed twice in quick
succession.
> Keyboard.enter_text: Add 1s interpress delay when entering the same letter twice

- _stbt/logging.py
If running inside a Jupyter Notebook, display debug images inline.
I don't know what to do about the HTML output (including regions we draw
over an image using CSS) but at least we'll see some of the debug
information.
> ImageLogger: Add support for Jupyter Notebooks

- _stbt/transition.py
This is best practice because it may be more accurate.
> docs: Use time from `stbt.press`

- _stbt/core.py
- stbt/__init__.py
- tests/test-stbt-py.sh
We already set `_stbt.core.DeviceUnderTest._last_keypress`, but we don't expose it in a public API.
> Add stbt.last_keypress()

- _stbt/ocr.py
- _stbt/utils.py
- stbt/__init__.py
- tests/test_ocr.py
A dict of {bad: good} mappings to correct known OCR mistakes.
TODO:
Out of scope for this pull request:
- Also `stbt.match_text`? But it could be tricky if the pattern to replace spans multiple hocr xml elements.
> stbt.ocr: Add `corrections` parameter

- _stbt/core.py
`appsrc` does its own buffering, and won't reject frames even if the sink
pipeline isn't running or is in an error state.  This can lead to memory
exhaustion.  This will at least avoid OOM, even if the sink pipeline will
have to be fixed seperately.
100MB is 1.4s at 720p25.
TODO:
> sink pipeline: Avoid filling up RAM if something goes wrong

- _stbt/imgutils.py
- _stbt/ocr.py
We still support Python 2 but the docs we publish assume Python 3.
> docstrings: Replace "unicode" => "str"

- stbt/keyboard.py
- tests/test_keyboard.py
`networkx.parse_edgelist` treats "#" as a comment by default.
If I do `comments=None` or `comments=False` I get a TypeError. If I do
`comments=""` I get a graph without any nodes at all. So I have used a
long random string as the comment marker.
> stbt.Keyboard: Allow key names with "#" in them

- _stbt/logging.py
You might have a notebook that does its own visualisation, and you don't
want every `stbt.match` (etc) to be logging tons of debug. In that case
you can put `_stbt.logging._jupyter_logging_enabled = False` at the top
of your notebook.
> ImageLogger: Allow disabling image logging in Jupyter Notebook

- _stbt/black.py
- _stbt/stbt.conf
This is what >90% of our customers are using (and the rest are using a higher threshold).
> stbt.is_screen_black: Increase default threshold to 20

- _stbt/control_gpl.py
- stbt_control_relay.py
To handle cases where the destination device disappears and then reappears with a different number.
> HdmiCecControl: Re-scan CEC bus if transmit fails

- _stbt/logging.py
Just for convenience. I use it like this:
from _stbt.logging import imshow
imshow(f)
> Add private API _stbt.logging.imshow for Jupyter Notebooks

- stbt_core/pylint_plugin.py
- tests/test-stbt-lint.sh
It's a mistake to think that `refresh()` modifies the instance in place.
FrameObjects are immutable.
> pylint plugin: Verify that FrameObject refresh() return value is used

- _stbt/keyboard.py
So that you can override it:
kb = stbt.Keyboard()
kb.symmetrical_keys["KEY_1"] = "KEY_2"
kb.symmetrical_keys["KEY_2"] = "KEY_1"
I don't know what the use-case would be, so I won't document this, but it gives us some flexibility to modify the default behaviour without having to make a new Stb-tester release.
> stbt.Keyboard: Make `symmetrical_keys` dict a member of Keyboard

- _stbt/keyboard.py
So that callers can override it if they need to provide a custom
implementation (for example to handle live video behind a translucent
background). I won't document this for now, but it gives us some
flexibility without having to make a new Stb-tester release.
This is an interim measure until we iron out the "Movable" API in
<https://github.com/stb-tester/stb-tester/pull/695>.
> stbt.Keyboard: Add press_and_wait member

- _stbt/imgutils.py
- tests/test_core.py
This seems like more useful behaviour. We can call `crop` with `Region.ALL`, or with regions from `above/below/right_of/left_of` which might have an infinite height/width.
We do still raise for an empty region. I considered returning an empty slice, but what purpose would that serve? And at what position do we return it -- `frame[0:0, 0:0]`? Note that the previous implementation would also raise: `r.contains(None)` => False.
> stbt.crop: Implicitly crop at edge of frame, instead of raising

- _stbt/black.py
- _stbt/diff.py
- _stbt/imgutils.py
- _stbt/match.py
- _stbt/ocr.py
- _stbt/types.py
- tests/test_core.py
- tests/test_ocr.py
- tests/test_stbt_debug.py
For `ocr` and `match_text` this is a change in behaviour: Previously if the region was entirely outside of the frame, they would log a warning and return "" or a Falsey TextMatchResult, respectively (but for `region=None` they would already raise a TypeError). I don't think the old behaviour is anything you'd ever want to do intentionally, it's far more likely to be a bug in your test. And the new behaviour is consistent with all the other stbt APIs.
For all the other functions this is a nicer error message. `press_and_wait` would raise "UnboundLocalError: local variable 'f1' referenced before assignment". The others would raise either "ValueError: frame with dimensions (720, 1280, 3) doesn't contain None" (from stbt.crop) or "AttributeError: 'NoneType' object has no attribute …
> ocr, match_text: Raise exception if region is outside of frame

- _stbt/diff.py
- _stbt/imgutils.py
- _stbt/motion.py
- _stbt/transition.py
- tests/test_match.py
- tests/test_motion.py
- tests/test_ocr.py
- tests/test_transition.py
When testing an Xfinity set-top-box, I think it was, pressing OK on a button caused that button to "blip" briefly for a single frame or 2, then followed by no motion, before actually starting the transition to the new page. Sometimes that period of no motion was longer than 1 second, so it would fool `press_and_wait` into thinking the transition had completed before it had even started.
Setting `stable_secs` to a very large number isn't ideal, as it would slow down all test-runs for the sake of handling this intermittent behaviour.
TODO:
> stbt.press_and_wait: Add min_size parameter

- _stbt/ocr.py
So that we can see the exact timestamp of the frame that was
processed (not the timestamp when the debug message was printed).
> stbt.ocr: Include frame_repr in debug output

- _stbt/imgutils.py
If an image is in the test pack then we will print the name relative to
the test-pack root.  This is more useful for logging as it's unambiguous
which image is being used.
> Image logging: Use relative_filename where appropriate

- _stbt/ocr.py
- setup.py
Saves having to download and install `libxml2` with pip.  We usually
can't use ocr with pip installed package anyway as we can't express
a dependency on tesseract.
> pip package: Make lxml and Jinja optional dependencies

- _stbt/core.py
Error was:
File "/usr/lib/python3/dist-packages/_stbt/core.py", line 1009, in on_warning
self.source_pipeline, Gst.DebugGraphDetails.ALL, "WARNING")
TypeError: Argument 0 does not allow None as a value
> Pipeline: Fix error on `GST_ELEMENT_WARNING`

- _stbt/core.py
- tests/test-stbt-py.sh
This behaviour was introduced to handle the VidiU's H.264 encoder restart (see commit 6b7ba0a "stbt.py: Handle VidiU H.264 encoder restart"). As far as we know, the only VidiU user (YouView) had some kind of repeater / HDMI doctor in between the STB and the VidiU, which provided a continuous signal even when the STB rebooted or changed mode, thus avoiding this behaviour from the VidiU.
I'm removing it because:
- It isn't used (as per the previous paragraph).
- It complicates the implementation.
- It obscures real problems with the source pipeline.
- It interacts poorly with the sink pipeline: the recorded video ends up corrupted, with wrong timestamps, or huge gaps, with lots of errors in the logs.
Now we ignore the EOS; `get_frame` will soon time out and raise `NoVideo`.
> core: Don't restart source pipeline on EOS

- Makefile
- _stbt/keyboard.py
- setup.py
I've had a little difficulty with it on Windows.  It's not necessary
for pylint to work as it's no-longer exposed in our APIs.
> pip package: Make networkx an optional dependency

- stbt_core/__init__.py
* Saving a frame to disk with `cv2.imwrite` was documented in our manual but repeating it here will make the information easier to find.
* The behaviour of `stbt.get_frame` re. blocking (or the lack thereof) wasn't documented anywhere.
> stbt.frames, get_frame docstrings: Add more information & examples

- _stbt/imgutils.py
- tests/test_core.py
Recently I had a reference image that I wanted to anchor to the left edge of the frame like this:
image = stbt.load_image(...)
stbt.match(image, region=stbt.Region(x=0, width=image.shape[1], ...))
...so that if I had to update the reference image in future I wouldn't have to update the Python code to match the new width.
By providing `width` and `height` properties, we don't have to expose the numpy details of `shape` and its unintuitive coordinate order.
> stbt.Image: Add `width` and `height` properties

- Makefile
- _stbt/multipress.py
- stbt_core/__init__.py
- tests/test_multipress.py
In some apps, the search page allows entering text by pressing the keys
on the remote control's numeric keypad: press the number "2" once for
"A", twice for "B", etc.:
1.,     ABC2    DEF3
GHI4    JKL5    MNO6
PQRS7   TUV8    WXYZ9
[space]0
This is much easier (and faster) than moving a selection around an
on-screen keyboard.
The keys for A-Z are specified in [ITU E.161]. The standard doesn't
specify where "space" goes, but every implementation I have seen has it
on KEY_0. Punctuation varies across implementations; I have arbitrarily
chosen the behaviour of a Sky HD+ box that I had available for testing,
but you can override this by passing `key_mapping={"KEY_1": "@1.,-_}` to
the `stbt.MultiPress` constructor.
[ITU E.161]: https://www.itu.int/rec/T-REC-E.161
> Add stbt.MultiPress: Enter text using a numeric keypad

- _stbt/imgutils.py
- tests/test_core.py
Similar to the recent commit 656a59f2d3a4 "stbt.Image: Add `width` and
`height` properties", but for `stbt.Frame`.
Recently I was checking for the width of a region obtained with
`right_of`. But this region has infinite width, so I needed to intersect
it with the size of the frame, but this isn't currently possible without
reaching into `shape` which is numpy-specific and has unintuitive
coordinate order. Now I can do something like
`r.right_of().replace(right=self._frame.right)`.
Note that the current documentation of `right_of` is incorrect, or at
least misleading: "Returns: A new region to the right of the current
region, extending **to the right edge of the frame** (or to the
specified width)" -- emphasis mine.
> stbt.Frame: Add `width` and `height` properties

- _stbt/imgutils.py
- tests/test_core.py
...when the Image or Frame has gone through numpy operations that change
its shape (such as `numpy.max`, which will preserve the `stbt.Image` or
`stbt.Frame` type of its argument).
Fixes #717.
> stbt.Image, stbt.Frame: Fix IndexError in __repr__

- _stbt/android.py
- _stbt/core.py
- _stbt/frameobject.py
- _stbt/imgutils.py
- _stbt/keyboard.py
- _stbt/match.py
- _stbt/pylint_plugin.py
- _stbt/stbt_run.py
- extra/pylint.conf
- stbt_control_relay.py
- tests/conftest.py
- tests/test_keyboard.py
- tests/test_ocr.py
- tests/test_stbt_debug.py
I was testing the Search keyboard on a Comcast Xfinity box. This has the keys in a single line A - Z so there can be a lot of keypresses to get to the next letter. When `verify_every_keypress=False`, the selection can settle on one of the intermediate letters for long enough to trick our `stable_secs=0.5`, causing the test to fail. After the test failed, the selection carried on moving and did reach the expected target.
I tried increasing stable_secs to 1. This made it fail less often, but it still happens sometimes. Setting `verify_every_keypress=True` fixes this problem but makes it intolerably slow. I don't want to increase stable_secs for every letter because this would slow it down unnecessarily in the usual, successful case.
> stbt.Keyboard: More robust for slow/buggy keyboards

- _stbt/core.py
- stbt_core/__init__.py
- tests/test-lirc.sh
To support user-defined enums like this:
class Keys(enum.Enum):
KEY_0 = "KEY_0"
KEY_1 = "KEY_1"
...
stbt.press(Keys.KEY_0)
Defining such an enum (it can be auto-generated from your lircd.conf file) allows your IDE to provide linting & auto-complete suggestions.
> stbt.press, stbt.pressing: Support Enum values for the key name

- _stbt/ocr.py
- tests/test_ocr.py
>>> stbt.apply_ocr_corrections("itv+", {"itv+": "Apple tv+"})
itv+ 
The above should return `"Apple tv+"` but it doesn't change the input text at all. Something to do with word boundaries? Plain strings are supposed to match whole words or phrases but not be interpreted as regexes.
> Fix OCR corrections bug: Complete string doesn't match if it ends in non-word character

- _stbt/keyboard.py
- tests/test_keyboard.py
If your Page Object is buggy, and it returns `is_visible=True` but `selection=None` we'd get an inscrutable TypeError from the depths of our implementation:
File "_stbt/keyboard.py", line 707, in _keys_to_press
for s, t in zip(path[:-1], path[1:]):
TypeError: unhashable type: 'slice'
This is because we call `networkx.shortest_path(G, source, target)`. Normally it returns a list, but when `source` is None it returns a dict (with the shortest path for each node in the graph to `target`, keyed by the starting node).
> stbt.Keyboard: Better error message when page.selection is None

- .circleci/ubuntu2004.dockerfile
- _stbt/android.py
- _stbt/control.py
- _stbt/core.py
- _stbt/cv2_compat.py
- _stbt/frameobject.py
- _stbt/grid.py
- _stbt/gst_hacks.py
- _stbt/gst_utils.py
- _stbt/imgproc_cache.py
- _stbt/irnetbox.py
- _stbt/keyboard.py
- _stbt/logging.py
- _stbt/match.py
- _stbt/ocr.py
- _stbt/pylint_plugin.py
- _stbt/stbt_run.py
- _stbt/utils.py
- stbt_core/__init__.py
- tests/test_lirc_control.py
- tests/test_match.py
- tests/test_ocr.py
- tests/test_stbt_control_relay.py
- tests/vstb-example-html5/tests/rotate.py
I found these by running pylint with `--enable=useless-suppression`.
I learned of this in the pylint documentation:
https://pylint.pycqa.org/en/latest/user_guide/message-control.html#detecting-useless-disables
> As pylint gets better and false positives are removed, disables that became useless can accumulate and clutter the code. In order to clean them you can enable the useless-suppression warning.
I haven't enabled `useless-suppression` permanently in pylint.conf because it says that the `line-too-long` annotations in `tests/test_keyboard.py` are useless, but if I remove the annotations then pylint complains that the lines are too long.
Tested with Ubuntu 20.04's pylint which is what we use in CI:
❯ pylint --version
pylint 2.4.4
astroid 2.3.3
> Remove useless pylint annotations

- _stbt/frameobject.py
- tests/test_frameobject.py
The bugs in `__eq__` and `__ne__` were:
- If one of the properties returned `None`, `__cmp__` would raise `TypeError: '<' not supported between instances of 'NoneType' and '<type of other.property>'`.
One way to trigger this was to call `wait_until(MyFrameObjectClass, stable_secs=1)`. Because of `stable_secs` we compare the return value of successive calls and if one of the properties was None it would raise `TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'`.
- If comparing an instance of F vs. an instance of FF, where FF is a subclass of F, if you put the subclass first you could get incorrect results (i.e. `f == ff` worked, but `ff == f` didn't). This is because `__cmp__` would return `NotImplemented` and we'd end up comparing `NotImplemented` against 0 (which …
> FrameObject: Fix __eq__, remove ordering operators

- _stbt/ocr.py
- tests/test_ocr.py
Spaces aren't the only word boundaries. This fixes an (unreleased) regression introduced in commit 5ecd51f (#731).
> stbt.ocr corrections: Fix matching word boundary

- _stbt/core.py
It's excessive and I don't recall a situation where this has ever been useful.
> core: Remove ddebug on every sample

- _stbt/black.py
- _stbt/diff.py
- _stbt/imgutils.py
- _stbt/keyboard.py
- _stbt/motion.py
- _stbt/transition.py
- extra/pylint.sh
- stbt_core/__init__.py
- tests/test-irnetbox.sh
This enables:
```python
SPINNER = stbt.Region(34, 433, right=44, bottom=444)
stbt.wait_for_motion(mask=mask_out(SPINNER))
```
There is an interesting overlap here with #624.  Conceptually `mask_out(Region.ALL)` is `Region.NONE`.
**TODO:**
- Tests for passing `region and `mask_out(Region)` to
> Pass regions and the inverse as mask= parameters

- _stbt/imgutils.py
- _stbt/ocr.py
- extra/pylint.sh
- stbt_core/__init__.py
- tests/test-stbt-py.sh
- tests/test_core.py
- tests/test_ocr.py
- tests/test_stbt_debug.py
So far we have been specifying colors as (blue, green, red) tuples. This supports that same format, but also supports the more user-friendly and familiar "#rrggbb" format in a string.
TODO:
> Add Color type

- Makefile
- _stbt/black.py
- _stbt/diff.py
- _stbt/imgutils.py
- _stbt/keyboard.py
- _stbt/mask.py
- _stbt/motion.py
- _stbt/transition.py
- _stbt/types.py
- stbt_core/__init__.py
- stbt_run.py
- tests/test-gstreamer-installation.sh
- tests/test-lirc.sh
- tests/test-motion.sh
- tests/test-stbt-lint.sh
- tests/test-stbt-py.sh
- tests/test_core.py
- tests/test_mask.py
- tests/utils.sh
TODO:
- ~Fix circular imports. Perhaps move all of Mask into types.py (or all of Region into mask.py) and move stuff out of `__init__` into `load_mask` in imgutils.py?~ Nah it's fine, we just do `from imgutils import load_image` inside `__init__()` and `to_array()`, not at the module top level.
Future:
- Implement `Mask.bounding_region` and make all our APIs use it to save processing time; eventually `mask=Region(...)` can replace the `region` parameter in our APIs.
> Add Mask type supporting +, -, and ~

- _stbt/transition.py
- tests/test_transition.py
This allows us to write:
transition = stbt.press_and_wait(...)
assert transition.stable
or even this:
assert stbt.press_and_wait(...).stable
instead of this, which is cumbersome:
assert transition.status != stbt.TransitionStatus.STABLE_TIMEOUT
Another useful example is:
if not transition.started:        
...
...to detect if we've reached the end of a menu because the keypress had no effect. `assert stbt.press_and_wait(...)` isn't suitable because it would fail due to START_TIMEOUT. For example see bc46fcc.
TODO:
> TransitionResult: Add started/complete/stable properties

- _stbt/match.py
- tests/test_stbt_debug.py
...instead of showing only the part that's cropped to `region`.
This fixes the position of the match region drawn onto the frame, if you specified `region`.
Also, use our existing `ImageLogger._draw_annotated_image` infrastructure for drawing these regions. This will also add a purple rectangle showing the input `region`, and it uses CSS to draw the rectangles instead of creating another PNG.
Fixes #705.
Manual testing:
> match: Show full sized frame in html debug

- _stbt/imgutils.py
- _stbt/mask.py
- stbt_core/__init__.py
Users often have trouble finding a file committed to git in the test-pack, such as a csv file with data needed by the test.
> Make `find_file` a public API

- _stbt/imgutils.py
- _stbt/mask.py
- tests/test_mask.py
`Mask.to_array` is memoized so if the user modifies the array in-place it would affect the array we return from future calls to `to_array`.
The `load_image` change was made late in the v33 release and I'm nervous it hasn't been tested enough. We can revisit for v34.  `wait_for_motion(mask="a filename.png")` will still memoize the mask (because `Mask.to_array` has its own memoization) but `wait_for_match("a filename.png")` won't.
> load_image: Remove memoization; Mask.to_array: Make the array read-only

- _stbt/match.py
- _stbt/ocr.py
In case there are changes in behaviour due to new Tesseract / OpenCV versions.
Regarding stbt.match: In spite of the new `matchTemplate` implementation in OpenCV 4.4, we have extensive tests that check the match position, and none of those tests have required changes. Maybe the `first_pass_result` could vary very slightly, resulting in a change in behaviour when it was already very close to the threshold?
> match, ocr: imgproc_cache cache-buster for v33

- _stbt/frameobject.py
This helps pylint to infer the correct type.
> FrameObject.refresh: Use self.__class__ instead of type(self)

- _stbt/android.py
- _stbt/logging.py
For example DEBUG:stbt.Keyboard:This is the message...
This is the default format if you call `logging.basicConfig()` without specifying a format (though it's not the default format when you create a Formatter explicitly: see <https://stackoverflow.com/a/72801269>).
This is the (undocumented) `logging.BASIC_FORMAT`.
I'm changing it so that it's more likely to match the user's own logging. If you call `logging.info` (or debug etc) it'll automatically call `logging.basicConfig()`.
> logging: Use Python's default logging format

- _stbt/frameobject.py
- tests/test_frameobject.py
To avoid triggering expensive calculations.
> FrameObject repr: Only print values of properties already calculated

- _stbt/frameobject.py
- _stbt/imgutils.py
- tests/test_core.py
- tests/test_frameobject.py
- tests/test_motion.py
So that you can see the frame timestamp associated with the FrameObject, click on it to see that frame in the video, etc.
> FrameObject repr: Show self._frame

- _stbt/black.py
- _stbt/core.py
- _stbt/imgutils.py
- _stbt/motion.py
- _stbt/transition.py
Note: stacklevel=2 shows the line of code that called is_screen_black (etc) instead of the line of code in is_screen_black itself that is calling `warnings.warn`.
stacklevel=1:
_stbt/black.py:72: DeprecationWarning: stbt.is_screen_black: The 'region' parameter is deprecated; pass your Region to 'mask' instead
warnings.warn(
stacklevel=2:
test.py:4: DeprecationWarning: stbt.is_screen_black: The 'region' parameter is deprecated; pass your Region to 'mask' instead
print(stbt.is_screen_black(region=stbt.Region(0,0,100,100)))
I also changed the warnings filter so that these messages actually get shown. The "default" action prints the warning once per (file, line number) — i.e. once per call-site.
> Print deprecation warning for deprecated "region" parameter

- _stbt/keyboard.py
It was more than deprecated; it raised an exception if you tried to use it. I have made the remaining parameters keyword-only, for clearer error message if you're upgrading old code from v31 directly to v33 skipping v32.
> Keyboard: Remove deprecated `graph` parameter

- _stbt/black.py
- _stbt/diff.py
To support numpy arrays that aren't a `stbt.Frame`. We'd probably never hit this outside our own selftests but no need to introduced a breaking change if we don't need to.
> is_screen_black, MotionDiff: Use _image_region instead of frame.region

- _stbt/diff.py
- _stbt/motion.py
- tests/masks.ipynb
- tests/test_transition.py
> d = numpy.logical_and(d, mask_pixels)
> ValueError: operands could not be broadcast together with shapes (720,1280) (720,1280,3)
None of the regions in our unit test actually resulted in a pixel mask -- they were all "simple" masks that could be expressed as a region.
> BGRDiff: Fix mask number of channels

- _stbt/control.py
The first keypress can take a while if the lircd (or stbt-control-relay) process is socket-activated and hasn't started yet.
> LIRC control: Increase socket timeout

- _stbt/pylint_plugin.py
- tests/test-stbt-lint.sh
Astroid represents `f"{var} - selected.png"` like this:
JoinedStr(values=[
FormattedValue(value=<Name.var>),
Const.str(value=" - selected.png")
])
Without this commit, we'd report a false positive:
> E:  6,20: Image " - selected.png" not found on disk (stbt-missing-image)
> stbt lint: stbt-missing-image: Fix false positive for f-strings

- _stbt/wait.py
- stbt_run.py
- tests/test-pytest.sh
This allows running your test-scripts with pytest, to get pytest's features (in particular [assertion introspection] and [fixtures]).
[assertion introspection]: https://docs.pytest.org/en/6.2.x/assert.html
[fixtures]: https://docs.pytest.org/en/7.1.x/explanation/fixtures.html#about-fixtures
> Convert stbt_run.py to be a pytest plugin 

- _stbt/android.py
Also clarify that `AdbError` is from `stbt`, not `subprocess`.
> AdbDevice.adb docstring: Document that we raise subprocess.TimeoutExpired

- _stbt/mask.py
- tests/test_mask.py
Useful when you have a reference image with some transparent parts, but you want to use that same mask for an operation other than `match`.
> Mask: Add `from_alpha_channel` constructor

- _stbt/core.py
- _stbt/transition.py
- _stbt/types.py
- tests/test_transition.py
Consistent with `wait_for_motion`.  This will allow performing some transformation on the video before it's processed by `wait_for_motion`.
> API: press_and_wait/wait_for_transition_to_end: Add public frames parameter

- _stbt/wait.py
Useful for ad-hoc performance measurements after the fact, or speeding up slow test scripts.
> wait_until: Log how long it took

- _stbt/motion.py
- _stbt/stbt.conf
- _stbt/transition.py
- tests/stbt.conf
- tests/test-motion.sh
- tests/test_motion.py
- tests/test_stbt_debug.py
The previous default (GrayscaleDiff) doesn't detect changes that are different in colour but of a similar overall intensity, such as the XFinity keyboard shown in `tests/test_diff.py::test_bgrdiff`.
> Make BGRDiff the default for press_and_wait / detect_motion / wait_for_motion

- _stbt/logging.py
- _stbt/transition.py
- tests/test_transition.py
If the keypress had no effect at all, retry this number of times. Defaults to 0, so you have to opt-in to this behaviour by specifying, say, `retries=1` or `retries=2`.
Useful for devices with a tendency to miss keypresses.
TODO:
- ~stbt.Keyboard.navigate_to passes its own `retries` into `press_and_wait`.~ Doesn't make sense because `navigate_to` uses `press`, not `press_and_wait`.
> press_and_wait: Add retries parameter

- _stbt/diff.py
- _stbt/mask.py
- _stbt/motion.py
- _stbt/transition.py
- _stbt/types.py
- stbt_core/__init__.py
- tests/conftest.py
- tests/test_diff.py
- tests/test_transition.py
Instead of subclassing `FrameDiffer` we now subclass `Differ` and pass an
instance of that subclass to `FrameDiffer`.  So before you'd write:
press_and_wait.differ = BGRDiff
and now it's
press_and_wait.differ = BGRDiff()
This means that we can customise differ parameters by passing arguments to
the constructor like:
press_and_wait.differ = BGRDiff(threshold=60)
To support this differs are now immutable.  The `previous_frame` state that
used to live in `BGRDiff` and `GreyscaleDiff` is now implemented in
`FrameDiffer` which is now a concrete class.
We still need to support passing differ parameters directly to
`press_and_wait`, etc. like `press_and_wait(min_size=...)`, so there's a
`.replace` argument which returns a new differ, but with those parameters
set.
`Differ` is designed so we can …
> Refactor: Replace subclassing FrameDiffer with subclassing Differ

- MANIFEST.in
- Makefile
- _stbt/diff.py
- _stbt/libstbt.py
- _stbt/match.py
- _stbt/sqdiff.c
- _stbt/sqdiff.py
- docs/release-notes.md
- tests/test_diff.py
This removes a bunch of large temporary arrays from the BGRDiff hot path. From looking at godbolt it looks like it vectorises well too.
This code is basically untested.  More testing required.  Raising now for profiling.
> BGRDiff: Implement inner loop in C

- _stbt/control_gpl.py
- stbt_core/__init__.py
We tend to use "KEY_GUIDE" as it's clearer than a cryptic acronym.
> HdmiCecControl: Add "KEY_GUIDE" alias for "KEY_EPG"

- _stbt/grid.py
- _stbt/keyboard.py
- tests/test_keyboard.py
For example: this keyboard has a 3 square wide space bar and a two square wide OK button on the bottom row:
KEYBOARD = stbt.Keyboard()
KEYBOARD.add_grid(
stbt.Grid(
stbt.Region(377, 476, 527, 228),
data=[
"qwertyuiop",
"asdfghjkl,",
["CAPS"] + list("zxcvbnm.") + ["BACKSPACE"],
["?123"] + list("◀▶   -_") + ["OK"] * 2,
]
),
mode="lower", merge=True
)
Without this change you'd have to separately add space and ok as separate keys and explicitly list the transitions up, left and right.  This is much less verbose and more readable.  See the changes to the tests to see.
> Keyboard.add_grid: Merge identical adjacent keys

- _stbt/black.py
- _stbt/config.py
- _stbt/grid.py
- _stbt/imgutils.py
- _stbt/keyboard.py
- _stbt/mask.py
- _stbt/match.py
- _stbt/motion.py
- _stbt/multipress.py
- _stbt/ocr.py
- _stbt/precondition.py
- _stbt/transition.py
- _stbt/types.py
- _stbt/wait.py
- stbt_core/__init__.py
* Don't use `Tuple/List/Dict`, use `tuple/list/dict` instead
* Don't use `Union`, use `|` instead
* Use `Optional[T]` only in parameters where `None` means "use the default
value", rather than when `None` is a meaningful value by itself.  For
instance: `region=None` means select nothing - as `None` is a valid
region, while `frame=None` means grab a frame from live.  None is just
a placeholder.  This means that we never use `Optional` in a return value
position.
* Fix missing use of `Optional` in a few places
* Add a few more type annotations
> Better typing

- _stbt/control_gpl.py
On the FireTV stick (and less frequently, on some other STBs) we intermittently have `stbt.press()` failing:
> DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
We have seen these errors on keydown and keyup. As far as I remember, every time the keypress did actually take effect. We think TRANSMIT_FAILED_ACK means that we didn't get the ACK signal (I think the ACK is implemented by the receiver holding the voltage level high on the CEC wire for a certain amount of time).
Unfortunately libcec's `Transmit` doesn't give us any information about why it failed; it just returns True or False.
> HdmiCecControl: Don't fail if libcec Transmit fails

- _stbt/keyboard.py
- _stbt/transition.py
- stbt_core/__init__.py
- tests/test_keyboard.py
- tests/test_transition.py
Needed for type annotations on navigation functions etc.
I have called it "Transition" instead of "TransitionResult" because having "TransitionResult" and "TransitionStatus" (the enum) is too confusing. Now there's confusion between "Transition" vs. "_Transition" (the latter is a private helper class) but at least the confusion is limited to the internal implementation details in `transition.py`.
> Expose `Transition` (return type of `press_and_wait`) as public API

- _stbt/imgutils.py
The "/" was added in commit 9e73a7850 (load_image typing: Ensure that color_channels is passed by name). The commit message suggests that the intention is for color_channels to be a keyword-only argument. But "/" means positional-only: https://peps.python.org/pep-0570/
> load_image: Fix typing overload: color_channels is keyword-only

- _stbt/imgutils.py
This was causing an exception when sphinx was trying to evaluate the type annotations:
> name 'Optional' is not defined
Note that we use `from __future__ import annotations` in this file so we don't need to quote the annotations.
> Color: Fix type annotation

- _stbt/keyboard.py
- tests/test_keyboard.py
"focus" is going to be our official name going forward; "selection" is ambiguous because you can have "selected" something and then move the "focus" somewhere else without changing the active "selection".
I'm adding this to Keyboard for consistency with [navigate_1d].
For backwards compatibility we use the `selection` property, if it exists (even if `focus` also exists, to avoid changing behaviour for existing users, in case they have both a `focus` and a `selection`, even though it seems unlikely... but doing it this way means we can release this in a v34 minor release).
[navigate_1d]: https://stb-tester.com/manual/python-api#stbt.navigate_1d
> Keyboard: Suport Page Object with `focus` property instead of `selection`

- _stbt/ocr.py
- tests/test_ocr.py
There's a subtlety when adding your own replacements, if the replaced value is itself already a key in the replacements. Previously, you would have to do this:
ocr_eq.replacements["İ"] = "I"                    # incorrect!
ocr_eq.replacements["İ"] = ocr_eq.normalise("I")  # correct
Now, `ocr_eq.replacements["İ"] = "I"` is correct.
If a user replaces `ocr_eq.replacements` wholesale with a new dict, it'll lose this behaviour; but then that's their problem. Either replace it once with a single dict that you don't modify, or add to our one.
Note: I subclass [collections.UserDict] instead of subclassing `dict` directly, so that `copy()` preserves my subclass type (needed for my unit tests).
[collections.UserDict]: https://docs.python.org/3/library/collections.html#collections.UserDict
> ocr_eq.replacements: Custom __setitem__

- _stbt/config.py
This way VSCode knows that `ip_address is not None` in this case:
ip_address = stbt.get_config("device_under_test", "ip_address")
> get_config: Better type annotations

- _stbt/config.py
This helped me to debug why configparser's `getboolean` was failing. The error message now looks like this:
> 'global.should_also_be_true' invalid type (must be bool): Not a boolean: yes  # with a comment
"Not a boolean: yes  # with a comment" is from the ValueError. As an aside, it made me realise that Python 3's configparser disables inline comments by default.
> get_config: Improve error message when type conversion fails

- _stbt/ocr.py
- tests/test_ocr.py
I have seen Tesseract return "Music:" (with a trailing colon) instead of "Music" — admittedly I was doing my own binarisation, but the binarised image looked 100% correct.
> ocr_eq: Ignore punctuation

- _stbt/ocr.py
If you pass a `Region` to `ocr_eq.normalize` it used to raise a confusing error:
>>> ocr_eq.normalize(stbt.Region(0, 0, 1, 1))
TypeError: '<=' not supported between instances of 'int' and 'str'
Now it says:
TypeError: stbt.ocr_eq.normalize: Expected a str, got Region(x=0, y=0, right=1, bottom=1)
> ocr_eq: Produce a better error message if given non-string

- _stbt/black.py
- _stbt/core.py
- _stbt/logging.py
- _stbt/match.py
- _stbt/ocr.py
So we can show which regions are being ocred in the object repo.
> Internal: Add `logging.draw_source_region`

- _stbt/keyboard.py
- tests/test_keyboard.py
If there are two "A"s in the keyboard, it should succeed if it can find a path to one of them.
For convenience I'm modelling a Keyboard that has 2 different appearances (on different STBs) as a single Keyboard with 2 different modes (and a single Page Object that handles both appearances). Both modes have all the letters, and there's no way to get from one mode to the other. This way I don't have to make my Page Object remember which `Keyboard` instance to use — there's only one `Keyboard` instance.
> stbt.Keyboard: Allow disjoint modes

- _stbt/keyboard.py
- tests/test_keyboard.py
This fixes a quadratic algorithm when adding keys, because each time we added a key, we scanned through the entire list of keys to check that it wasn't already present.
Defining a keyboard is typically done at module import time, not at run time, so we want it to be as fast as possible, even if it doesn't seem like much.
> Keyboard: performance optimisations for defining a keyboard

- _stbt/control.py
> LircRemote: Close temporary connection to lircd promptly on error

- _stbt/android.py
> android: Set permissions of adb secret key to 0600

- _stbt/android.py
This is https://stb-tester.com/manual/logs
We're recommending to use a pytest autouse fixture for log capture, instead of decorating every test function.
> android.AdbDevice.logcat: Link to "Capturing logs" page in the manual

- _stbt/android.py
Older versions of `adb shell` would convert every LF in the PNG data to CRLF. Apparently newer versions of adb don't do this, so our "fix" actually corrupts the PNG and we get "AdbError: Failed to capture screenshot from android device".
https://stackoverflow.com/a/13593914:
> It's worth noting that the PNG file format is explicitly designed to catch exactly this (and related) problems. The magic number begins with 0x89 to catch anything that strips high bits, followed by "PNG" so you can easily tell what's in the file, followed by CR LF to catch various ASCII line converters, then 0x1a to trap old MS-DOS programs that used Ctrl-Z as a special end-of-file marker, and then a lone LF. By looking at the first few bytes of the file you can tell exactly what was done to it.
> AdbDevice.get_frame: Handle PNG data not corrupted by adb shell

- _stbt/core.py
- tests/test_press.py
This allows mapping key names in the config file.
Example:
[control]
keymap_section = mykeymap
[mykeymap]
KEY_UP = KEYCODE_DPAD_UP
And now when you call `stbt.press("KEY_UP")` actually `KEYCODE_DPAD_UP` will get sent.
> Add control.keymap_section config variable

- _stbt/config.py
- _stbt/core.py
- _stbt/imgutils.py
- _stbt/keyboard.py
- _stbt/match.py
- _stbt/ocr.py
- _stbt/transition.py
- stbt_core/__init__.py
- stbt_virtual_stb.py
- tests/test_config.py
- tests/test_ocr.py
- tests/test_press.py
This allows overriding the default language for a particular device type. This will be particularly useful for OCR properties in the Object Repository.
> ocr & get_config changes for Object Repository

- _stbt/config.py
- _stbt/ocr.py
- stbt_virtual_stb.py
- tests/test_config.py
- tests/test_ocr.py
Revert a couple of changes from #851:
- You can just specify an `[ocr]` section in your node-specific config file, no need for a new config.
- We decided that changing the configparser interpolation is too risky.
> Revert #851

- _stbt/imgutils.py
...always supported, just wasn't in the type annotations.
> Color: typing: Add overload for passing a single `Color` argument
