stb-tester/stb-tester

README.rst, stbt-run
=> stbt run -h: Document that you can specify a python function to run

stbt-camera.d/gst/stbtcontraststretch.c
This commit deals with error condition like missing png file
during camera calibration.
=> stbtcontraststretch: Fix error while loading a missing png file

stbt-camera.d/stbt-camera-calibrate.py, stbt-camera.d/stbt-camera-validate.py
=> Camera: fix endless analysis

_stbt/tv_driver.py
This commit fixes typo in comment.
=> tv_driver.py: Fix typo in comment

_stbt/core.py
This is useful when you have a function which returns a region of non-fixed size and you just want to take the top of it.  E.g.:
title_region = find_info_region.replace(height=64)
**TODO:**
- ~~Update release notes~~ (I think the existing release note for Region.replace --which is new in the next release-- is sufficient).
=> stbt: Teach Region.replace() about width and height

.travis.yml, tests/test-stbt-batch.sh, tests/test-stbt-control.sh, tests/test-stbt-py.sh
See http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/
This commit is to test whether we get Ubuntu 14.04 even though we don't actually use docker.
TODO:
=> .travis.yml: Use Travis CI's new docker infrastructure

_stbt/core.py, docs/release-notes.md, stbt/__init__.py, tests/test-match.sh
...much like `stbt.match` already does.
TODO:
=> stbt.wait_for_match: Take `region` parameter

CONTRIBUTING.md, Makefile, _stbt/core.py, _stbt/state_watch.py, docs/release-notes.md, extra/debian/test-deb.sh, extra/fedora/Dockerfile.in, extra/fedora/stb-tester.spec.in, extra/fedora/test-rpm.sh, stbt/__init__.py, tests/test-stbt-run.sh
=> Prepare for v24 release

.gitignore, CONTRIBUTING.md, MAINTAINERS.md, Makefile, README.md, docs/stbt.1.rst, extra/fedora/README.md, stbt.sh.in
=> Move man page out of README

_stbt/core.py
=> Add debug output to match_text

docs/release-notes.md
They seem to have got a little confused with two "New Features" sections.
As an aside I do notice that we seem to have a fantastic set of new features since v24 so maybe it'd be worth doing a release soon.
=> Tidy up release notes

stbt_auto_selftest.py
3 Miscellaneous improvements split out of #354
=> Auto selftest improvements

Makefile, _stbt/core.py, _stbt/logging.py
Extracted from #212 and rebased on top of master to resolve conflicts from #354.
=> ImageLogger refactorings in preparation for implementing `match_all`

_stbt/control_gpl.py, docs/stbt.1.rst
=> HDMI CEC: Automatically choose device to talk to

_stbt/pylint_plugin.py, docs/release-notes.md, tests/test-stbt-lint.sh
=> stbt lint: Check that frameobjects pass self._frame

_stbt/core.py, docs/release-notes.md, tests/test_core.py
=> stbt.wait_until: Add `predicate` parameter

extra/debian/control, extra/fedora/stb-tester.spec.in, stbt-batch, stbt-batch.d/run-one, stbt-batch.d/run.py
Continuing the saga of pythonising `stbt batch run`.  This should be faster as there is less spawning processes.  I'd like to be able to replace all the little files with a single JSON file and this refactor.
=> Refactor stbt batch run

tests/stbt-debug-expected-output/match/00001/index.html, tests/stbt-debug-expected-output/match/00002/index.html, tests/stbt-debug-expected-output/match/00003/index.html, tests/stbt-debug-expected-output/match/00004/index.html, tests/test_match.py
To catch regressions like #472.
=> Add characterization tests for stbt.match debug html

_stbt/stbt_run.py, tests/test-stbt-run.sh
This fixes an unreleased regression introduced in d920296 from #471.
=> stbt-run: Save the screenshot attached to the exception, if any

Makefile, stbt-batch.d/post-run.sh, stbt-batch.d/print_backtrace.gdb, stbt-batch.d/run-one, stbt-batch.d/run.py, tests/test-stbt-batch.sh
For better maintainability and speed.  With this change we will be spawning many fewer processes.  In particular all the (fairly slow) calls to `stbt config` from bash are removed.
=> Pythonize stbt batch run

stbt-batch.d/run.py, stbt.conf, tests/test-stbt-batch.sh
From the recent rewrite in Python (#495).
=> Fix stbt batch regressions

_stbt/frameobject.py, _stbt/match.py, _stbt/motion.py, _stbt/ocr.py
Similar to `namedtuple`, and useful for the same reasons:
https://docs.python.org/2/library/collections.html#collections.somenamedtuple._fields
=> stbt.FrameObject: Add _fields attribute

_stbt/power.py, stbt-power
Like the ATEN this is controlled over SNMP.
I haven't written any tests for it.  I don't really believe in the value
of the existing ATEN tests so I don't want to duplicate them.  A better
approach might be to use [snmpsim] or similar to mock out the PDU at the
SNMP layer.
I also haven't investigated the failure modes of the PDU.
This is a bit rough, but could form the basis for a more mature implementation.
[snmpsim]: http://snmplabs.com/snmpsim/index.html
=> Rittal power support

_stbt/match.py, docs/release-notes.md
=>  stbt.MatchParameters API docs: More details about match methods & thresholds

tests/run_performance_test.py
It was testing the system-wide stbt, not the one in the source directory!
=> run_performance_test.py: Fix stbt import path

_stbt/transition.py
For consistency with `stbt.press`.
=> stbt.press_and_wait: Add `key` attribute to the return value

_stbt/motion.py, tests/test_motion.py
`wait_for_motion` has a `noise_threshold` intended to exclude false
positives when looking for motion.  By default if any pixel changes in
intensity by less than 40 per frame (e.g. takes longer than 250ms to go
from black to white) motion will not be detected.
This commit fixes this issue by not strictly looking at consecutive frames,
instead it will compare the current frame to the last one where motion was
seen.  This allows differences to accumulate over time.  In theory noise
will be decorrelated with time so there will be no accumulation of error,
whereas actual motion will be correlated with time, so we will detect the
motion.
Here's a comparison of the old and new implementations.  In both cases a
difference of above 40 will be considered motion.  The old impl never
fires, the new …
=> wait_for_motion: Do better at detecting slow motion

stbt/keyboard.py, tests/test_keyboard.py
This makes the keyboard entry a bit zippier.
=> stbt.Keyboard: Reduce press_and_wait stable_secs to 0.5

_stbt/frameobject.py, _stbt/imgutils.py, _stbt/wait.py, stbt/pylint_plugin.py
=> FrameObject docs: Link to more modern FrameObject tutorial

_stbt/black.py, _stbt/imgutils.py, _stbt/motion.py, _stbt/ocr.py, _stbt/wait.py, stbt/__init__.py, stbt/android.py
v29 is the oldest version still used by any of our customers.
=> docstrings: Remove "Added/changed in" for changes pre-dating v29

.circleci/config.yml, setup.py, tests/test_core.py
=> setup.py: Add missing dependency "attrs"

_stbt/keyboard.py, tests/test_keyboard.py
People were doing `from _stbt.keyboard import Key` so that they could use `Key` in type annotations for their page object's `selection` property.
TODO:
=> stbt.Keyboard: Make stbt.Keyboard.Key part of the public API

_stbt/android.py, tests/test-stbt-py.sh
=> android: Add Stb-tester key names for NVidia Shield remote control

_stbt/logging.py, _stbt/types.py, stbt_core/__init__.py, tests/test-stbt-py.sh
For things like `min_size` and `max_size` -- in fact anything with only a width & height.
=> Add `Size` type

_stbt/imgutils.py, _stbt/mask.py, tests/test-match.sh, tests/test-motion.sh, tests/test-stbt-match.sh, tests/test-stbt-run.sh, tests/test_core.py, tests/utils.sh
Fix for bug mentioned here: https://github.com/stb-tester/stb-tester/pull/447#issuecomment-316455645
=> Fix IOError printing

_stbt/config.py, _stbt/diff.py, _stbt/match.py, _stbt/motion.py, _stbt/ocr.py, _stbt/transition.py
And some other miscellaneous fixes, gearing up for v33 release.
TODO:
=> wait_for_motion: Make differ algorithm configurable

_stbt/imgutils.py
Colors are supposed to be immutable.
=> Color: Make `array` member read-only

_stbt/types.py, stbt_core/__init__.py
For APIs such as segmentation that process the image in a particular direction (horizontal or vertical).
=> Add type stbt.Direction

tests/test-stbt-py.sh
CircleCI was extremely slow. We aren't using it since #751.
=> integration tests: Revert long timeouts for CircleCI

_stbt/core.py
Just some tidy-ups I had on an old branch.
=> interpress_delay refactorings

_stbt/wait.py
=> wait_until: Add type annotations

_stbt/motion.py, _stbt/transition.py
This was missing from commit c28c6f0a.
=> press_and_wait, wait_for_motion docstrings: Document algorithm change

_stbt/power.py
Uses the `kasa` command-line tool from python-kasa: https://github.com/python-kasa/python-kasa/
=> _stbt.power: Support TP-Link "Kasa" smart plugs

_stbt/power.py, tests/test_power.py
...overriding `device_under_test.power_outlet` from the config.
=> config_to_power_outlet: Add power_outlet parameter

_stbt/ocr.py, tests/test_ocr.py
Seen when testing navigation on real Apple TV & Roku devices, plus all the suggestions from https://stackoverflow.com/a/58098360.
=> ocr_eq: more replacements
